#include "Session.h"
#include "catalog/type_registry.h"
#include "commands/DdlExecutor.h"
#include "commands/TableManage.h"
#include "parser/parser.h"
#include "test_utils.h"

#include <algorithm>
#include <cassert>
#include <iostream>
#include <sstream>

extern dbms::StorageEngine g_engine;

int main() {
    using dbms::DBStatus;
    dbms::TypeRegistry::instance().bootstrap();
    const std::string name = "conflicting_nullability";
    const std::string database = testDbPath(name);
    cleanupTestDb(name);
    assert(g_engine.createDatabase(database, "utf8") == DBStatus::OK);
    Session session;
    session.username = "testuser";
    session.permission = 1;
    session.currentDB = database;
    dbms::DdlExecutor ddl;
    dbms::SQLParser parser;
    for (const auto* declaration : {"INT NULL NOT NULL", "INT NOT NULL NULL",
                                   "INT PRIMARY KEY NULL", "INT NULL PRIMARY KEY",
                                   "INT GENERATED ALWAYS AS IDENTITY NULL",
                                   "INT NULL GENERATED BY DEFAULT AS IDENTITY"}) {
        const std::string sql = "CREATE TABLE bad(id " + std::string(declaration) + ")";
        const auto parsed = parser.parse(sql);
        assert(parsed.success);
        const auto* table = dynamic_cast<const dbms::CreateTableStmt*>(parsed.stmt.get());
        assert(table && table->columns.size() == 1);
        const auto& constraints = table->columns[0].constraints;
        assert(std::find(constraints.begin(), constraints.end(), "NULL") != constraints.end());
        std::ostringstream diagnostic;
        auto* old = std::cout.rdbuf(diagnostic.rdbuf());
        const bool failed = ddl.executeSql(sql, session);
        std::cout.rdbuf(old);
        assert(failed && diagnostic.str().find("42601") != std::string::npos);
        assert(!g_engine.tableExists(database, "bad"));
    }
    // PostgreSQL treats a later table-level primary key differently from
    // contradictory inline column declarations. Preserve the legal case.
    assert(!ddl.executeSql("CREATE TABLE good(id INT NULL,PRIMARY KEY(id))", session));
    assert(!g_engine.getTableSchema(database, "good").cols[0].isNull);
    assert(g_engine.insert(database, "good", {{"id", "1"}}) == DBStatus::OK);
    assert(g_engine.insertRow(database, "good", {{"id", std::nullopt}}) == DBStatus::NULL_NOT_ALLOWED);
    assert(!ddl.executeSql("DROP TABLE good", session));
    const auto nullable = parser.parse("CREATE TABLE nullable(id INT DEFAULT NULL)");
    assert(nullable.success);
    const auto* table = dynamic_cast<const dbms::CreateTableStmt*>(nullable.stmt.get());
    assert(table && table->columns[0].constraints.empty());
    cleanupTestDb(name);
    finalCleanupTestData();
    std::cout << "[CONFLICTING NULLABILITY] passed\n";
}
