#!/usr/bin/env python3
"""Conflicting inline NULL declarations fail without changing the table."""

import importlib.util
from pathlib import Path


def main():
    root = Path(__file__).resolve().parent.parent
    spec = importlib.util.spec_from_file_location(
        "nullability_pgdiff", root / "tests" / "compat" / "pg_diff_runner.py")
    runner = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(runner)
    client = runner.load_protocol_client()
    server = runner.start_ours(client)

    def query(sql, rows=None, state=None, ready=b"I"):
        messages = client.simple_query(server["sock"], sql)
        result = runner.decode_wire_result(messages)
        assert result[1] == state, (sql, result)
        assert messages[-1] == (b"Z", ready), (sql, messages[-1])
        if rows is not None:
            assert result[0] == rows, (sql, result[0], rows)

    try:
        for declaration in ("INT NULL NOT NULL", "INT NOT NULL NULL",
                            "INT PRIMARY KEY NULL", "INT NULL PRIMARY KEY",
                            "INT GENERATED ALWAYS AS IDENTITY NULL",
                            "INT NULL GENERATED BY DEFAULT AS IDENTITY"):
            query(f"CREATE TABLE bad_null(id {declaration});", [], "42601")
            query("SELECT id FROM bad_null;", [], "42P01")
        query("CREATE TABLE nullability_prior(base INT);")
        query("BEGIN;", ready=b"T")
        query("INSERT INTO nullability_prior VALUES(7);", ready=b"T")
        for declaration in ("INT NULL NOT NULL", "INT NOT NULL NULL"):
            query("SAVEPOINT kept;", ready=b"T")
            query(f"ALTER TABLE nullability_prior ADD COLUMN id {declaration};", [], "42601", b"E")
            query("SELECT 1;", [], "25P02", b"E")
            query("ROLLBACK TO SAVEPOINT kept;", ready=b"T")
            query("SELECT base FROM nullability_prior;", [["7"]], ready=b"T")
            query("RELEASE SAVEPOINT kept;", ready=b"T")
        query("COMMIT;")
        query("CREATE TABLE table_pk_nullable(id INT NULL,PRIMARY KEY(id));")
        query("INSERT INTO table_pk_nullable VALUES(NULL);", [], "23502")
        query("INSERT INTO table_pk_nullable VALUES(1) RETURNING id;", [["1"]])
        query("CREATE TABLE ordinary_nullable(id INT NULL DEFAULT NULL);")
        query("INSERT INTO ordinary_nullable DEFAULT VALUES RETURNING id;", [[None]])
        print("[CONFLICTING NULLABILITY PROTOCOL E2E] passed")
    finally:
        runner.stop_ours(server)


if __name__ == "__main__":
    main()
