// ============================================================================
// CREATE TABLE options test — Phase 4 Wave 4.26
// Verifies LIKE INCLUDING (CONSTRAINTS, INDEXES, IDENTITY), identity columns,
// and PARTITION BY wiring from DDL AST to the engine.
// ============================================================================

#include "commands/DdlExecutor.h"
#include "commands/TableManage.h"
#include "Session.h"
#include "catalog/type_registry.h"
#include <cassert>
#include <filesystem>
#include <iostream>
#include "test_utils.h"

extern dbms::StorageEngine g_engine;

namespace fs = std::filesystem;

static void cleanup(const std::string& db) { if (std::filesystem::exists(db)) std::filesystem::remove_all(db); }

static void setupSession(Session& s, const std::string& db) {
    s.username = "testuser";
    s.permission = 1;
    s.currentDB = db;
}

static const dbms::Column* findCol(const dbms::TableSchema& t, const std::string& name) {
    for (size_t i = 0; i < t.len; ++i)
        if (t.cols[i].dataName == name) return &t.cols[i];
    return nullptr;
}

// LIKE INCLUDING CONSTRAINTS copies CHECK constraints but not PK/DEFAULT/IDENTITY.
static void test_like_including_constraints() {
    std::string db = testDbPath("opts_like_chk");
    cleanup(db);
    assert(g_engine.createDatabase(db, "utf8") == dbms::DBStatus::OK);
    Session s; setupSession(s, db);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql(
        "CREATE TABLE src (id INT PRIMARY KEY, price INT DEFAULT 10, "
        "CONSTRAINT chk_pos CHECK (price > 0))", s));
    assert(!ddl.executeSql(
        "CREATE TABLE cpy (LIKE src INCLUDING CONSTRAINTS)", s));

    auto schema = g_engine.getTableSchema(db, "cpy");
    const dbms::Column* id = findCol(schema, "id");
    const dbms::Column* price = findCol(schema, "price");
    assert(id && price);
    assert(!id->isPrimaryKey);                  // PK not copied
    assert(price->defaultValue.empty());        // default not copied
    // CHECK constraints are stored on column 0 (first column).
    assert(!id->checkExpr.empty());             // CHECK copied
    cleanup(db);
    std::cout << "[OPTS] LIKE INCLUDING CONSTRAINTS OK" << std::endl;
}

// LIKE INCLUDING INDEXES copies PK and UNIQUE but not DEFAULT/CHECK/IDENTITY.
static void test_like_including_indexes() {
    std::string db = testDbPath("opts_like_idx");
    cleanup(db);
    assert(g_engine.createDatabase(db, "utf8") == dbms::DBStatus::OK);
    Session s; setupSession(s, db);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql(
        "CREATE TABLE src (id INT PRIMARY KEY, email VARCHAR(50) UNIQUE, "
        "score INT DEFAULT 0)", s));
    assert(!ddl.executeSql(
        "CREATE TABLE cpy (LIKE src INCLUDING INDEXES)", s));

    auto schema = g_engine.getTableSchema(db, "cpy");
    const dbms::Column* id = findCol(schema, "id");
    const dbms::Column* email = findCol(schema, "email");
    const dbms::Column* score = findCol(schema, "score");
    assert(id && email && score);
    assert(id->isPrimaryKey);                   // PK copied
    assert(email->isUnique);                    // UNIQUE copied
    assert(score->defaultValue.empty());        // default not copied
    cleanup(db);
    std::cout << "[OPTS] LIKE INCLUDING INDEXES OK" << std::endl;
}

// LIKE INCLUDING IDENTITY copies auto-increment flag.
static void test_like_including_identity() {
    std::string db = testDbPath("opts_like_id");
    cleanup(db);
    assert(g_engine.createDatabase(db, "utf8") == dbms::DBStatus::OK);
    Session s; setupSession(s, db);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql(
        "CREATE TABLE src (id INT GENERATED ALWAYS AS IDENTITY, name VARCHAR(20))", s));
    assert(!ddl.executeSql(
        "CREATE TABLE cpy (LIKE src INCLUDING IDENTITY)", s));

    auto schema = g_engine.getTableSchema(db, "cpy");
    const dbms::Column* id = findCol(schema, "id");
    const dbms::Column* name = findCol(schema, "name");
    assert(id && name);
    assert(id->isAutoIncrement);                // identity copied
    assert(!name->isAutoIncrement);             // non-identity stays false
    cleanup(db);
    std::cout << "[OPTS] LIKE INCLUDING IDENTITY OK" << std::endl;
}

// GENERATED ALWAYS AS IDENTITY sets isAutoIncrement.
static void test_identity_always() {
    std::string db = testDbPath("opts_id_always");
    cleanup(db);
    assert(g_engine.createDatabase(db, "utf8") == dbms::DBStatus::OK);
    Session s; setupSession(s, db);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql(
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY, val INT)", s));

    auto schema = g_engine.getTableSchema(db, "t");
    const dbms::Column* id = findCol(schema, "id");
    assert(id);
    assert(id->isAutoIncrement);
    cleanup(db);
    std::cout << "[OPTS] GENERATED ALWAYS AS IDENTITY OK" << std::endl;
}

// GENERATED BY DEFAULT AS IDENTITY also sets isAutoIncrement.
static void test_identity_by_default() {
    std::string db = testDbPath("opts_id_default");
    cleanup(db);
    assert(g_engine.createDatabase(db, "utf8") == dbms::DBStatus::OK);
    Session s; setupSession(s, db);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql(
        "CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY, val INT)", s));

    auto schema = g_engine.getTableSchema(db, "t");
    const dbms::Column* id = findCol(schema, "id");
    assert(id);
    assert(id->isAutoIncrement);
    cleanup(db);
    std::cout << "[OPTS] GENERATED BY DEFAULT AS IDENTITY OK" << std::endl;
}

// PARTITION BY RANGE through DDL sets partition metadata, then engine routes rows.
static void test_partition_by_range_ddl() {
    std::string db = testDbPath("opts_part_range");
    cleanup(db);
    assert(g_engine.createDatabase(db, "utf8") == dbms::DBStatus::OK);
    Session s; setupSession(s, db);
    dbms::DdlExecutor ddl;

    // Create partitioned table through DDL.
    assert(!ddl.executeSql(
        "CREATE TABLE sales (id INT, yr INT) PARTITION BY RANGE (yr)", s));

    // Verify partition metadata was wired.
    auto schema = g_engine.getTableSchema(db, "sales");
    assert(schema.partitionKey == "yr");
    assert(schema.partitionType == dbms::TableSchema::PartitionType::Range);

    // Attach partitions via engine API (PARTITION OF not yet parsed).
    assert(g_engine.attachPartition(db, "sales", "p2020",
        "FOR VALUES FROM (2020) TO (2021)") == dbms::DBStatus::OK);
    assert(g_engine.attachPartition(db, "sales", "p2025",
        "FOR VALUES FROM (2025) TO (2026)") == dbms::DBStatus::OK);

    // Insert rows and verify routing.
    assert(g_engine.insert(db, "sales", {{"id", "1"}, {"yr", "2020"}}) == dbms::DBStatus::OK);
    assert(g_engine.insert(db, "sales", {{"id", "2"}, {"yr", "2025"}}) == dbms::DBStatus::OK);

    auto rows = g_engine.query(db, "sales", {}, {"id", "yr"});
    assert(rows.size() == 2);

    cleanup(db);
    std::cout << "[OPTS] PARTITION BY RANGE via DDL OK" << std::endl;
}

// PARTITION BY LIST through DDL.
static void test_partition_by_list_ddl() {
    std::string db = testDbPath("opts_part_list");
    cleanup(db);
    assert(g_engine.createDatabase(db, "utf8") == dbms::DBStatus::OK);
    Session s; setupSession(s, db);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql(
        "CREATE TABLE events (id INT, region VARCHAR) PARTITION BY LIST (region)", s));

    auto schema = g_engine.getTableSchema(db, "events");
    assert(schema.partitionKey == "region");
    assert(schema.partitionType == dbms::TableSchema::PartitionType::List);

    // Attach list partitions.
    assert(g_engine.attachPartition(db, "events", "east",
        "FOR VALUES IN ('NY', 'NJ')") == dbms::DBStatus::OK);
    assert(g_engine.attachPartition(db, "events", "west",
        "FOR VALUES IN ('CA', 'OR')") == dbms::DBStatus::OK);

    assert(g_engine.insert(db, "events", {{"id", "1"}, {"region", "NY"}}) == dbms::DBStatus::OK);
    assert(g_engine.insert(db, "events", {{"id", "2"}, {"region", "CA"}}) == dbms::DBStatus::OK);

    auto rows = g_engine.query(db, "events", {}, {"id", "region"});
    assert(rows.size() == 2);

    cleanup(db);
    std::cout << "[OPTS] PARTITION BY LIST via DDL OK" << std::endl;
}

// PARTITION BY HASH through DDL.
static void test_partition_by_hash_ddl() {
    std::string db = testDbPath("opts_part_hash");
    cleanup(db);
    assert(g_engine.createDatabase(db, "utf8") == dbms::DBStatus::OK);
    Session s; setupSession(s, db);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql(
        "CREATE TABLE htbl (id INT, key VARCHAR) PARTITION BY HASH (key)", s));

    auto schema = g_engine.getTableSchema(db, "htbl");
    assert(schema.partitionKey == "key");
    assert(schema.partitionType == dbms::TableSchema::PartitionType::Hash);

    cleanup(db);
    std::cout << "[OPTS] PARTITION BY HASH via DDL OK" << std::endl;
}

// Tablespace is stored in schema.
static void test_tablespace_option() {
    std::string db = testDbPath("opts_ts");
    cleanup(db);
    assert(g_engine.createDatabase(db, "utf8") == dbms::DBStatus::OK);
    Session s; setupSession(s, db);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql("CREATE TABLE t (id INT) TABLESPACE pg_default", s));

    auto schema = g_engine.getTableSchema(db, "t");
    assert(schema.tablespace == "pg_default");
    cleanup(db);
    std::cout << "[OPTS] TABLESPACE stored in schema OK" << std::endl;
}

int main() {
    dbms::TypeRegistry::instance().bootstrap();
    test_like_including_constraints();
    test_like_including_indexes();
    test_like_including_identity();
    test_identity_always();
    test_identity_by_default();
    test_partition_by_range_ddl();
    test_partition_by_list_ddl();
    test_partition_by_hash_ddl();
    test_tablespace_option();
    std::cout << "[OPTS] all passed" << std::endl;
    return 0;
}
