#include "commands/DdlExecutor.h"
#include "commands/DmlExecutor.h"
#include "commands/TableManage.h"
#include "Session.h"
#include "catalog/catalog.h"
#include "catalog/CatalogService.h"
#include "parser/parser.h"
#include "test_utils.h"

#include <cassert>
#include <filesystem>
#include <iostream>
#include <sstream>
#include <string>

extern dbms::StorageEngine g_engine;

namespace {

void cleanup(const std::string& database) {
    std::error_code error;
    std::filesystem::remove_all(database, error);
}

void setupSession(Session& session, const std::string& database) {
    session.username = "testuser";
    session.permission = 1;
    session.currentDB = database;
}

bool runDml(const std::string& sql, Session& session,
            std::string* output = nullptr) {
    std::ostringstream captured;
    std::streambuf* previous = std::cout.rdbuf(captured.rdbuf());
    bool handled = false;
    const bool error = dbms::tryDmlBridge(
        sql, dbms::SQLParser::classify(sql), session, handled, sql);
    std::cout.rdbuf(previous);
    assert(handled);
    if (output) *output = captured.str();
    return error;
}

std::string value(const std::string& database, const std::string& table,
                  const std::string& condition, const std::string& column) {
    const auto rows = g_engine.query(database, table, {condition}, {column});
    assert(rows.size() == 1);
    const size_t end = rows.front().find_last_not_of(" \t\r\n");
    return end == std::string::npos ? std::string{} : rows.front().substr(0, end + 1);
}

void test_create_modes_and_overriding() {
    const std::string database = testDbPath("identity_modes");
    cleanup(database);
    assert(g_engine.createDatabase(database, "utf8") == dbms::DBStatus::OK);
    Session session;
    setupSession(session, database);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql(
        "CREATE TABLE always_t (id INTEGER GENERATED ALWAYS AS IDENTITY, note TEXT)",
        session));
    assert(!ddl.executeSql(
        "CREATE TABLE default_t (id BIGINT GENERATED BY DEFAULT AS IDENTITY, note TEXT)",
        session));

    auto alwaysSchema = g_engine.getTableSchema(database, "always_t");
    auto defaultSchema = g_engine.getTableSchema(database, "default_t");
    assert(alwaysSchema.cols[0].identityKind == 'a');
    assert(defaultSchema.cols[0].identityKind == 'd');
    assert(!alwaysSchema.cols[0].isNull && !defaultSchema.cols[0].isNull);

    const auto& catalog = g_engine.catalogService().get(database);
    const auto* alwaysRelation = catalog.resolveRelation("always_t", {"public"});
    const auto* defaultRelation = catalog.resolveRelation("default_t", {"public"});
    assert(alwaysRelation && defaultRelation);
    assert(catalog.findAttributes(alwaysRelation->oid).front().attidentity == 'a');
    assert(catalog.findAttributes(defaultRelation->oid).front().attidentity == 'd');

    assert(!runDml("INSERT INTO always_t (note) VALUES ('generated-1')", session));
    std::string output;
    assert(runDml("INSERT INTO always_t VALUES (50, 'rejected')", session, &output));
    assert(output.find("SQLSTATE 428C9") != std::string::npos);
    assert(runDml("INSERT INTO always_t VALUES (NULL, 'null-rejected')", session,
                  &output));
    assert(output.find("SQLSTATE 428C9") != std::string::npos);
    assert(!runDml(
        "INSERT INTO always_t OVERRIDING SYSTEM VALUE VALUES (50, 'system')",
        session));
    assert(!runDml(
        "INSERT INTO always_t OVERRIDING USER VALUE VALUES (99, 'generated-2')",
        session));
    assert(!runDml(
        "INSERT INTO always_t (id, note) VALUES (DEFAULT, 'generated-3')",
        session));
    assert(value(database, "always_t", "=note generated-1", "id") == "1");
    assert(value(database, "always_t", "=note system", "id") == "50");
    assert(value(database, "always_t", "=note generated-2", "id") == "2");
    assert(value(database, "always_t", "=note generated-3", "id") == "3");

    assert(!runDml("INSERT INTO default_t VALUES (40, 'explicit')", session));
    assert(!runDml("INSERT INTO default_t (note) VALUES ('generated-1')", session));
    assert(!runDml(
        "INSERT INTO default_t OVERRIDING USER VALUE VALUES (77, 'generated-2')",
        session));
    assert(!runDml(
        "INSERT INTO default_t OVERRIDING SYSTEM VALUE VALUES (41, 'system')",
        session));
    assert(value(database, "default_t", "=note explicit", "id") == "40");
    assert(value(database, "default_t", "=note generated-1", "id") == "1");
    assert(value(database, "default_t", "=note generated-2", "id") == "2");
    assert(value(database, "default_t", "=note system", "id") == "41");

    // The storage boundary enforces ALWAYS too; only an explicit system
    // override may bypass it, and USER means discard the supplied value.
    assert(g_engine.insert(database, "always_t",
                           {{"id", "60"}, {"note", "direct-rejected"}}) ==
           dbms::DBStatus::INVALID_VALUE);
    assert(g_engine.insert(database, "always_t",
                           {{"id", "60"}, {"note", "direct-system"}}, nullptr,
                           dbms::StorageEngine::IdentityOverride::System) ==
           dbms::DBStatus::OK);
    assert(g_engine.insert(database, "always_t",
                           {{"id", "999"}, {"note", "direct-user"}}, nullptr,
                           dbms::StorageEngine::IdentityOverride::User) ==
           dbms::DBStatus::OK);
    assert(value(database, "always_t", "=note direct-user", "id") == "4");

    cleanup(database);
    std::cout << "[IDENTITY] create modes and overriding OK\n";
}

void test_alter_identity_and_fail_closed_options() {
    const std::string database = testDbPath("identity_alter");
    cleanup(database);
    assert(g_engine.createDatabase(database, "utf8") == dbms::DBStatus::OK);
    Session session;
    setupSession(session, database);
    dbms::DdlExecutor ddl;

    assert(!ddl.executeSql("CREATE TABLE altered (id INTEGER NOT NULL, note TEXT)",
                           session));
    assert(!ddl.executeSql(
        "ALTER TABLE altered ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY",
        session));
    assert(g_engine.getTableSchema(database, "altered").cols[0].identityKind == 'a');
    assert(!runDml("INSERT INTO altered (note) VALUES ('one')", session));

    assert(!ddl.executeSql(
        "ALTER TABLE altered ALTER COLUMN id SET GENERATED BY DEFAULT", session));
    assert(!runDml("INSERT INTO altered VALUES (8, 'explicit')", session));
    assert(g_engine.getTableSchema(database, "altered").cols[0].identityKind == 'd');

    assert(!ddl.executeSql(
        "ALTER TABLE altered ALTER COLUMN id SET GENERATED ALWAYS", session));
    assert(runDml("INSERT INTO altered VALUES (9, 'rejected')", session));
    assert(!ddl.executeSql("ALTER TABLE altered ALTER COLUMN id DROP IDENTITY",
                           session));
    assert(!runDml("INSERT INTO altered VALUES (9, 'plain')", session));
    assert(ddl.executeSql("ALTER TABLE altered ALTER COLUMN id DROP IDENTITY",
                          session));
    assert(!ddl.executeSql(
        "ALTER TABLE altered ALTER COLUMN id DROP IDENTITY IF EXISTS", session));

    assert(ddl.executeSql(
        "ALTER TABLE altered ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY "
        "(START WITH 10)", session));
    assert(g_engine.getTableSchema(database, "altered").cols[0].identityKind == 0);

    assert(!ddl.executeSql("CREATE TABLE nullable_t (id INTEGER)", session));
    assert(ddl.executeSql(
        "ALTER TABLE nullable_t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY",
        session));
    assert(ddl.executeSql(
        "CREATE TABLE bad_type (id TEXT GENERATED ALWAYS AS IDENTITY)", session));
    assert(ddl.executeSql(
        "CREATE TABLE bad_default (id INTEGER DEFAULT 7 GENERATED ALWAYS AS IDENTITY)",
        session));
    assert(ddl.executeSql(
        "CREATE TABLE bad_options (id INTEGER GENERATED ALWAYS AS IDENTITY "
        "(START WITH 10))", session));

    dbms::SQLParser parser;
    assert(!parser.parse(
        "INSERT INTO altered OVERRIDING VALUE VALUES (1, 'x')").success);
    assert(!parser.parse(
        "INSERT INTO altered OVERRIDING SYSTEM VALUES (1, 'x')").success);

    cleanup(database);
    std::cout << "[IDENTITY] ALTER and fail-closed options OK\n";
}

} // namespace

int main() {
    test_create_modes_and_overriding();
    test_alter_identity_and_fail_closed_options();
    std::cout << "[IDENTITY] all passed\n";
    return 0;
}
