#include "parser/parser.h"
#include <cassert>
#include <iostream>

// Regression: command kinds reachable through SQLParser::classify().
// Locked after fixing a family of off-by-one prefix literals (aggregate,
// tablespace, publication, user mapping, prepare transaction, deallocate,
// fulltext index, ...) that silently misrouted statements into the
// CreateTable / DropTable fallbacks.
static void expectKind(const std::string& sql, dbms::SqlCommand want) {
    dbms::SqlCommand got = dbms::SQLParser::classify(sql);
    if (got != want) {
        dbms::Stmt gotStmt(got), wantStmt(want);
        std::cerr << "classify mismatch: " << sql
                  << " -> " << gotStmt.toString()
                  << " (want " << wantStmt.toString() << ")" << std::endl;
    }
    assert(got == want);
}

int main() {
    using dbms::SqlCommand;
    struct Case { const char* sql; SqlCommand want; };
    const Case cases[] = {
        {"create table t (a int)", SqlCommand::CreateTable},
        {"create index i on t (a)", SqlCommand::CreateIndex},
        {"create fulltext index fi on t (a)", SqlCommand::CreateFullTextIndex},
        {"create hash index hi on t (a)", SqlCommand::CreateHashIndex},
        {"create aggregate agg(int) (SFUNC = f, STYPE = int)", SqlCommand::CreateAggregate},
        {"create assertion a check (1 = 1)", SqlCommand::CreateAssertion},
        {"create server s1 foreign data wrapper dummy", SqlCommand::CreateServer},
        {"create user mapping for alice server s1", SqlCommand::CreateUserMapping},
        {"create user bob with password 'x'", SqlCommand::CreateUser},
        {"create tablespace ts location '/tmp'", SqlCommand::CreateTablespace},
        {"create publication p for all tables", SqlCommand::CreatePublication},
        {"create subscription s connection 'c' publication p", SqlCommand::CreateSubscription},
        {"create extension hstore", SqlCommand::CreateExtension},
        {"create database d", SqlCommand::CreateDatabase},
        {"create domain d as int", SqlCommand::CreateDomain},
        {"create sequence s", SqlCommand::CreateSequence},
        {"create view v as select 1", SqlCommand::CreateView},
        {"create materialized view mv as select 1", SqlCommand::CreateMaterializedView},
        {"create function f() returns int language sql as 'select 1'", SqlCommand::CreateFunction},
        {"create procedure p() language sql as 'select 1'", SqlCommand::CreateProcedure},
        {"create trigger tg before insert on t execute function f()", SqlCommand::CreateTrigger},
        {"create event trigger e on ddl_command_start execute function f()", SqlCommand::CreateEventTrigger},
        {"create rule r as on select to t do instead select 1", SqlCommand::CreateRule},
        {"create role r", SqlCommand::CreateRole},
        {"create group g", SqlCommand::CreateRole},
        {"create language plpgsql handler h", SqlCommand::CreateLanguage},
        {"create cast (int as text) with function f as implicit", SqlCommand::CreateCast},
        {"create collation c (locale = 'en_US')", SqlCommand::CreateCollation},
        {"create conversion c for 'a' to 'b' with function f", SqlCommand::CreateConversion},
        {"create operator class oc for type int using btree as operator 1 <", SqlCommand::CreateOperatorClass},
        {"create operator family ofam using btree", SqlCommand::CreateOperatorFamily},
        {"create access method am type table handler h", SqlCommand::CreateAccessMethod},
        {"create text search configuration c (parser = p)", SqlCommand::CreateTextSearchConfiguration},
        {"create text search dictionary d (template = t)", SqlCommand::CreateTextSearchDictionary},
        {"create transform for int language sql from sql with f", SqlCommand::CreateTransform},
        {"create schema s", SqlCommand::CreateSchema},
        {"create policy p on t using (true)", SqlCommand::CreatePolicy},
        {"create statistics s on a, b from t", SqlCommand::CreateStatistics},
        {"create type t as enum ('a')", SqlCommand::CreateType},
        {"drop table t", SqlCommand::DropTable},
        {"drop index i", SqlCommand::DropIndex},
        {"drop fulltext index fi on t", SqlCommand::DropFullTextIndex},
        {"drop aggregate agg(int)", SqlCommand::DropAggregate},
        {"drop assertion a", SqlCommand::DropAssertion},
        {"drop server s1", SqlCommand::DropServer},
        {"drop user mapping for alice server s1", SqlCommand::DropUserMapping},
        {"drop user bob", SqlCommand::DropUser},
        {"drop tablespace ts", SqlCommand::DropTablespace},
        {"drop publication p", SqlCommand::DropPublication},
        {"drop subscription s", SqlCommand::DropSubscription},
        {"drop extension hstore", SqlCommand::DropExtension},
        {"drop owned by bob", SqlCommand::DropOwned},
        {"drop large object 1234", SqlCommand::DropLargeObject},
        {"drop function f()", SqlCommand::DropFunction},
        {"drop procedure p()", SqlCommand::DropProcedure},
        {"drop routine r()", SqlCommand::DropRoutine},
        {"drop domain d", SqlCommand::DropDomain},
        {"drop sequence s", SqlCommand::DropSequence},
        {"drop type t", SqlCommand::DropType},
        {"drop trigger tg on t", SqlCommand::DropTrigger},
        {"drop event trigger e", SqlCommand::DropEventTrigger},
        {"drop rule r on t", SqlCommand::DropRule},
        {"drop language plpgsql", SqlCommand::DropLanguage},
        {"drop cast (int as text)", SqlCommand::DropCast},
        {"drop collation c", SqlCommand::DropCollation},
        {"drop conversion c", SqlCommand::DropConversion},
        {"drop operator + (int, int)", SqlCommand::DropOperator},
        {"drop operator class oc using btree", SqlCommand::DropOperatorClass},
        {"drop operator family ofam using btree", SqlCommand::DropOperatorFamily},
        {"drop access method am", SqlCommand::DropAccessMethod},
        {"drop text search configuration c", SqlCommand::DropTextSearchConfiguration},
        {"drop text search dictionary d", SqlCommand::DropTextSearchDictionary},
        {"drop transform for int language sql", SqlCommand::DropTransform},
        {"drop schema s", SqlCommand::DropSchema},
        {"drop policy p on t", SqlCommand::DropPolicy},
        {"drop statistics s", SqlCommand::DropStatistics},
        {"drop role r", SqlCommand::DropRole},
        {"drop group g", SqlCommand::DropRole},
        {"drop database d", SqlCommand::DropDatabase},
        {"drop view v", SqlCommand::DropView},
        {"drop materialized view mv", SqlCommand::DropMaterializedView},
        {"alter table t add column b int", SqlCommand::AlterTable},
        {"alter index i rename to i2", SqlCommand::AlterIndex},
        {"alter aggregate agg(int) rename to agg2", SqlCommand::AlterAggregate},
        {"alter server s1 rename to s2", SqlCommand::AlterServer},
        {"alter user mapping for alice server s1 options (add k 'v')", SqlCommand::AlterUserMapping},
        {"alter user bob with password 'x'", SqlCommand::AlterUser},
        {"alter tablespace ts rename to ts2", SqlCommand::AlterTablespace},
        {"alter publication p rename to p2", SqlCommand::AlterPublication},
        {"alter subscription s connection 'c'", SqlCommand::AlterSubscription},
        {"alter extension hstore update", SqlCommand::AlterExtension},
        {"alter system set work_mem = '64MB'", SqlCommand::AlterSystem},
        {"alter database d rename to d2", SqlCommand::AlterDatabase},
        {"alter schema s rename to s2", SqlCommand::AlterSchema},
        {"alter sequence s restart", SqlCommand::AlterSequence},
        {"alter domain d add constraint c check (value > 0)", SqlCommand::AlterDomain},
        {"alter type t rename to t2", SqlCommand::AlterType},
        {"alter view v rename to v2", SqlCommand::AlterView},
        {"alter function f() rename to f2", SqlCommand::AlterFunction},
        {"alter procedure p() rename to p2", SqlCommand::AlterProcedure},
        {"alter routine r() rename to r2", SqlCommand::AlterRoutine},
        {"alter trigger tg on t rename to tg2", SqlCommand::AlterTrigger},
        {"alter rule r on t rename to r2", SqlCommand::AlterRule},
        {"alter event trigger e disable", SqlCommand::AlterEventTrigger},
        {"alter role r with login", SqlCommand::AlterRole},
        {"alter statistics s set statistics 100", SqlCommand::AlterStatistics},
        {"alter policy p on t using (false)", SqlCommand::AlterPolicy},
        {"alter collation c rename to c2", SqlCommand::AlterCollation},
        {"alter conversion c rename to c2", SqlCommand::AlterConversion},
        {"alter operator + (int, int) owner to bob", SqlCommand::AlterOperator},
        {"alter operator class oc using btree rename to oc2", SqlCommand::AlterOperatorClass},
        {"alter operator family ofam using btree rename to ofam2", SqlCommand::AlterOperatorFamily},
        {"alter language plpgsql owner to bob", SqlCommand::AlterLanguage},
        {"alter large object 1234 owner to bob", SqlCommand::AlterLargeObject},
        {"alter text search configuration c rename to c2", SqlCommand::AlterTextSearchConfiguration},
        {"alter materialized view mv rename to mv2", SqlCommand::AlterMaterializedView},
        {"alter default privileges grant select on tables to r", SqlCommand::AlterDefaultPrivileges},
        {"select 1", SqlCommand::Select},
        {"insert into t values (1)", SqlCommand::Insert},
        {"update t set a = 1", SqlCommand::Update},
        {"delete from t", SqlCommand::Delete},
        {"copy t from stdin", SqlCommand::Copy},
        {"call p()", SqlCommand::Call},
        {"do $$ begin end $$", SqlCommand::Do},
        {"begin", SqlCommand::Begin},
        {"start transaction", SqlCommand::StartTransaction},
        {"commit", SqlCommand::Commit},
        {"commit prepared 'x'", SqlCommand::CommitPrepared},
        {"rollback", SqlCommand::Rollback},
        {"rollback prepared 'x'", SqlCommand::RollbackPrepared},
        {"rollback to savepoint sp", SqlCommand::RollbackToSavepoint},
        {"savepoint sp", SqlCommand::Savepoint},
        {"release savepoint sp", SqlCommand::ReleaseSavepoint},
        {"prepare transaction 'x'", SqlCommand::PrepareTransaction},
        {"abort", SqlCommand::Abort},
        {"end", SqlCommand::End},
        {"grant select on t to r", SqlCommand::Grant},
        {"revoke select on t from r", SqlCommand::Revoke},
        {"set statement_timeout = 1000", SqlCommand::Set},
        {"set role r", SqlCommand::SetRole},
        {"set session authorization bob", SqlCommand::SetSessionAuthorization},
        {"set constraints all deferred", SqlCommand::SetConstraints},
        {"set transaction isolation level serializable", SqlCommand::SetTransaction},
        {"show all", SqlCommand::Show},
        {"reset all", SqlCommand::Reset},
        {"use database d", SqlCommand::UseDatabase},
        {"use d", SqlCommand::UseDatabase},
        {"discard all", SqlCommand::Discard},
        {"explain select 1", SqlCommand::Explain},
        {"analyze t", SqlCommand::Analyze},
        {"vacuum t", SqlCommand::Vacuum},
        {"checkpoint", SqlCommand::Checkpoint},
        {"reindex table t", SqlCommand::Reindex},
        {"cluster t", SqlCommand::Cluster},
        {"comment on table t is 'x'", SqlCommand::Comment},
        {"security label on table t is 'x'", SqlCommand::SecurityLabel},
        {"lock t", SqlCommand::Lock},
        {"listen ch", SqlCommand::Listen},
        {"notify ch", SqlCommand::Notify},
        {"unlisten ch", SqlCommand::Unlisten},
        {"declare c cursor for select 1", SqlCommand::Declare},
        {"fetch next from c", SqlCommand::Fetch},
        {"move next from c", SqlCommand::Move},
        {"close c", SqlCommand::Close},
        {"prepare p as select 1", SqlCommand::Prepare},
        {"execute p", SqlCommand::Execute},
        {"deallocate p", SqlCommand::Deallocate},
        {"deallocate all", SqlCommand::Deallocate},
        {"import foreign schema fs from server s into public", SqlCommand::ImportForeignSchema},
        {"replace into t values (1)", SqlCommand::ReplaceInto},
        {"load data infile 'x' into table t", SqlCommand::LoadDataInfile},
        {"desc t", SqlCommand::Desc},
        {"view table t", SqlCommand::ViewTable},
        {"view database", SqlCommand::ViewDatabase},
        {"truncate t", SqlCommand::Truncate},
        {"values (1)", SqlCommand::Values},
    };
    for (const auto& c : cases) expectKind(c.sql, c.want);
    std::cout << "[CLASSIFY] all command classifications OK" << std::endl;
    return 0;
}
