DROP TABLE IF EXISTS diff_art_child;
DROP TABLE IF EXISTS diff_art_parent_new;
DROP TABLE IF EXISTS diff_art_parent;
CREATE TABLE diff_art_parent (id integer PRIMARY KEY);
CREATE TABLE diff_art_child (id integer REFERENCES diff_art_parent(id));
INSERT INTO diff_art_parent VALUES (1);
BEGIN;
ALTER TABLE diff_art_parent RENAME TO diff_art_parent_new;
INSERT INTO diff_art_child VALUES (1);
ROLLBACK;
SELECT id FROM diff_art_parent;
SELECT id FROM diff_art_parent_new;
INSERT INTO diff_art_child VALUES (1);
SELECT id FROM diff_art_child;
BEGIN;
SAVEPOINT rename_parent;
ALTER TABLE diff_art_parent RENAME TO diff_art_parent_new;
ROLLBACK TO SAVEPOINT rename_parent;
INSERT INTO diff_art_parent VALUES (2);
INSERT INTO diff_art_child VALUES (2);
COMMIT;
SELECT id FROM diff_art_child ORDER BY id;
ALTER TABLE diff_art_parent RENAME TO diff_art_parent_new;
INSERT INTO diff_art_parent_new VALUES (3);
INSERT INTO diff_art_child VALUES (3);
SELECT id FROM diff_art_child ORDER BY id;
