DROP TABLE IF EXISTS diff_arct;
CREATE TABLE diff_arct (id integer, old_name text);
INSERT INTO diff_arct VALUES (1, 'value');
CREATE INDEX diff_arct_name_idx ON diff_arct (old_name);
BEGIN;
ALTER TABLE diff_arct RENAME COLUMN old_name TO new_name;
SELECT new_name FROM diff_arct;
ROLLBACK;
SELECT old_name FROM diff_arct;
SELECT new_name FROM diff_arct;
BEGIN;
SAVEPOINT rename_point;
ALTER TABLE diff_arct RENAME COLUMN old_name TO temporary_name;
ROLLBACK TO SAVEPOINT rename_point;
SELECT old_name FROM diff_arct;
COMMIT;
SELECT temporary_name FROM diff_arct;
INSERT INTO diff_arct VALUES (2, 'later');
SELECT id FROM diff_arct WHERE old_name = 'later';
