DROP TABLE IF EXISTS diff_btw;
CREATE TABLE diff_btw (a INT);
INSERT INTO diff_btw VALUES (1), (2), (5), (NULL);
SELECT a BETWEEN 1 AND 2 FROM diff_btw;
SELECT a NOT BETWEEN 1 AND 2 FROM diff_btw;
SELECT a FROM diff_btw WHERE a BETWEEN 1 AND 2;
SELECT a FROM diff_btw WHERE a NOT BETWEEN 1 AND 2;
