CREATE TABLE diff_check_add(id INT PRIMARY KEY,value INT);
INSERT INTO diff_check_add VALUES(1,-1),(2,NULL);
ALTER TABLE diff_check_add ADD CONSTRAINT diff_check_positive CHECK(value > 0);
SELECT id,value FROM diff_check_add ORDER BY id;
INSERT INTO diff_check_add VALUES(3,-2);
BEGIN;
SAVEPOINT check_sp;
ALTER TABLE diff_check_add ADD CONSTRAINT diff_check_positive CHECK(value > 0);
SELECT id,value FROM diff_check_add;
ROLLBACK TO check_sp;
UPDATE diff_check_add SET value=1 WHERE value < 0;
ALTER TABLE diff_check_add ADD CONSTRAINT diff_check_positive CHECK(value > 0);
COMMIT;
INSERT INTO diff_check_add VALUES(4,NULL);
INSERT INTO diff_check_add VALUES(5,-1);
UPDATE diff_check_add SET value=-1 WHERE id=1;
SELECT id,value FROM diff_check_add ORDER BY id;
ALTER TABLE diff_check_add ADD COLUMN unpublished INT, ADD CONSTRAINT diff_check_upper CHECK(value < 0);
SELECT unpublished FROM diff_check_add;
SELECT id,value FROM diff_check_add ORDER BY id;
BEGIN;
SAVEPOINT rewrite_sp;
ALTER TABLE diff_check_add ADD COLUMN hidden INT, ADD CONSTRAINT diff_check_negative CHECK(value < 0);
ROLLBACK TO rewrite_sp;
SELECT hidden FROM diff_check_add;
ROLLBACK TO rewrite_sp;
COMMIT;
ALTER TABLE diff_check_add ADD COLUMN left_value INT, ADD COLUMN right_value INT;
SELECT id,value,left_value,right_value FROM diff_check_add ORDER BY id;
DROP TABLE diff_check_add;
