CREATE TABLE diff_commit_failure_parent(id INT PRIMARY KEY);
CREATE TABLE diff_commit_failure_child(id INT PRIMARY KEY,pid INT,CONSTRAINT commit_failure_fk FOREIGN KEY(pid) REFERENCES diff_commit_failure_parent(id) DEFERRABLE INITIALLY DEFERRED);
BEGIN;
INSERT INTO diff_commit_failure_child VALUES(1,999);
COMMIT;
SELECT id,pid FROM diff_commit_failure_child;
BEGIN;
INSERT INTO diff_commit_failure_child VALUES(2,999);
END;
SELECT id,pid FROM diff_commit_failure_child;
BEGIN;
INSERT INTO diff_commit_failure_child VALUES(2,999);
COMMIT AND CHAIN;
SELECT id,pid FROM diff_commit_failure_child;
BEGIN;
INSERT INTO diff_commit_failure_child VALUES(2,999);
PREPARE TRANSACTION 'diff_commit_failure_prepared';
SELECT id,pid FROM diff_commit_failure_child;
BEGIN;
SAVEPOINT diff_commit_failure_sp;
INSERT INTO diff_commit_failure_child VALUES(2,999);
SET CONSTRAINTS commit_failure_fk IMMEDIATE;
SELECT id FROM diff_commit_failure_child;
ROLLBACK TO SAVEPOINT diff_commit_failure_sp;
SELECT id,pid FROM diff_commit_failure_child;
COMMIT;
BEGIN;
INSERT INTO diff_commit_failure_parent VALUES(1);
INSERT INTO diff_commit_failure_child VALUES(1,1);
COMMIT;
SELECT id,pid FROM diff_commit_failure_child;
DROP TABLE diff_commit_failure_parent,diff_commit_failure_child;
CREATE TABLE diff_commit_failure_unique(id INT PRIMARY KEY,code INT,CONSTRAINT deferred_commit_unique UNIQUE(code) DEFERRABLE INITIALLY DEFERRED);
INSERT INTO diff_commit_failure_unique VALUES(1,5);
BEGIN;
INSERT INTO diff_commit_failure_unique VALUES(2,5);
COMMIT;
SELECT id,code FROM diff_commit_failure_unique;
DROP TABLE diff_commit_failure_unique;
