CREATE TABLE diff_rhs_sql_boundary(id INT PRIMARY KEY,code TEXT,d DATE);
INSERT INTO diff_rhs_sql_boundary VALUES(1,'1+2','2024-01-01'),(2,'2*3','2025-02-02');
SELECT id FROM diff_rhs_sql_boundary WHERE code='1+'||'2' ORDER BY id;
SELECT id FROM diff_rhs_sql_boundary WHERE d=CAST('2024-01-01' AS date) ORDER BY id;
SELECT id FROM diff_rhs_sql_boundary WHERE id=1+1 ORDER BY id;
UPDATE diff_rhs_sql_boundary SET code='updated' WHERE code='1+'||'2';
SELECT id,code FROM diff_rhs_sql_boundary ORDER BY id;
DELETE FROM diff_rhs_sql_boundary WHERE d=CAST('2025-02-02' AS date);
SELECT id,code,d FROM diff_rhs_sql_boundary ORDER BY id;
DROP TABLE diff_rhs_sql_boundary;
CREATE TABLE diff_delete_computed(id INT PRIMARY KEY,n NUMERIC,d DATE);
INSERT INTO diff_delete_computed VALUES(1,1,'2024-01-01'),(2,2,'2025-02-02'),(3,NULL,NULL);
DELETE FROM diff_delete_computed WHERE id=CAST(2 AS integer);
SELECT id FROM diff_delete_computed ORDER BY id;
TRUNCATE diff_delete_computed;
INSERT INTO diff_delete_computed VALUES(1,1,'2024-01-01'),(2,2,'2025-02-02'),(3,NULL,NULL);
DELETE FROM diff_delete_computed WHERE id=1+1;
SELECT id FROM diff_delete_computed ORDER BY id;
TRUNCATE diff_delete_computed;
INSERT INTO diff_delete_computed VALUES(1,1,'2024-01-01'),(2,2,'2025-02-02'),(3,NULL,NULL);
DELETE FROM diff_delete_computed WHERE d=CAST('2025-02-02' AS date);
SELECT id FROM diff_delete_computed ORDER BY id;
TRUNCATE diff_delete_computed;
INSERT INTO diff_delete_computed VALUES(1,1,'2024-01-01'),(2,2,'2025-02-02'),(3,NULL,NULL);
DELETE FROM diff_delete_computed WHERE CASE WHEN id=2 THEN true ELSE false END;
SELECT id FROM diff_delete_computed ORDER BY id;
TRUNCATE diff_delete_computed;
INSERT INTO diff_delete_computed VALUES(1,1,'2024-01-01'),(2,2,'2025-02-02'),(3,NULL,NULL);
DELETE FROM diff_delete_computed WHERE n/0.5>2;
SELECT id FROM diff_delete_computed ORDER BY id;
TRUNCATE diff_delete_computed;
INSERT INTO diff_delete_computed VALUES(1,1,'2024-01-01'),(2,2,'2025-02-02'),(3,NULL,NULL);
DELETE FROM diff_delete_computed WHERE coalesce(1,1/0)=1 AND id=2;
SELECT id FROM diff_delete_computed ORDER BY id;
TRUNCATE diff_delete_computed;
INSERT INTO diff_delete_computed VALUES(1,1,'2024-01-01'),(2,2,'2025-02-02'),(3,NULL,NULL);
DELETE FROM diff_delete_computed WHERE (id=1+1 OR id=4-1) AND id>1;
SELECT id FROM diff_delete_computed ORDER BY id;
DROP TABLE diff_delete_computed;
CREATE TABLE diff_delete_computed_error(id INT PRIMARY KEY,n NUMERIC);
INSERT INTO diff_delete_computed_error VALUES(1,1),(2,2);
DELETE FROM diff_delete_computed_error WHERE n/0>1;
SELECT id FROM diff_delete_computed_error ORDER BY id;
DELETE FROM diff_delete_computed_error WHERE id=CAST('bad' AS integer);
SELECT id FROM diff_delete_computed_error ORDER BY id;
DROP TABLE diff_delete_computed_error;
