DISCARD TEMP;
DROP INDEX pg_temp.diff_discard_temp_missing;
CREATE TEMP TABLE diff_discard_temp (id SERIAL, v TEXT);
INSERT INTO diff_discard_temp(v) VALUES('kept') RETURNING id;
PREPARE diff_discard_temp_keep AS SELECT 11;
DISCARD TEMP extra;
SELECT id,v FROM diff_discard_temp;
BEGIN;
DISCARD TEMPORARY;
SELECT id FROM diff_discard_temp;
ROLLBACK;
SELECT id,v FROM diff_discard_temp;
SELECT currval('diff_discard_temp_id_seq');
BEGIN;
SAVEPOINT before_discard;
DISCARD TEMP;
SELECT id FROM diff_discard_temp;
ROLLBACK TO before_discard;
SELECT id,v FROM diff_discard_temp;
COMMIT;
BEGIN READ ONLY;
DISCARD TEMP;
ROLLBACK;
SELECT id,v FROM diff_discard_temp;
DISCARD TEMP;
SELECT id FROM diff_discard_temp;
SELECT nextval('diff_discard_temp_id_seq');
DROP INDEX pg_temp.diff_discard_temp_missing;
EXECUTE diff_discard_temp_keep;
DEALLOCATE diff_discard_temp_keep;
DISCARD TEMP;
