CREATE TABLE diff_drop_group_parent(id INT PRIMARY KEY);
CREATE TABLE diff_drop_group_child(id INT PRIMARY KEY,pid INT REFERENCES diff_drop_group_parent(id));
DROP TABLE diff_drop_group_parent,diff_drop_group_child;
CREATE TABLE diff_drop_group_parent(id INT PRIMARY KEY);
CREATE TABLE diff_drop_group_child(id INT PRIMARY KEY,pid INT REFERENCES diff_drop_group_parent(id));
DROP TABLE diff_drop_group_child;
DROP TABLE diff_drop_group_parent;
CREATE TABLE diff_drop_group_parent(id INT PRIMARY KEY);
CREATE TABLE diff_drop_group_child(id INT PRIMARY KEY,pid INT REFERENCES diff_drop_group_parent(id));
CREATE TABLE diff_drop_group_survivor(id INT PRIMARY KEY,pid INT REFERENCES diff_drop_group_parent(id));
INSERT INTO diff_drop_group_parent VALUES(1);
INSERT INTO diff_drop_group_child VALUES(2,1);
INSERT INTO diff_drop_group_survivor VALUES(3,1);
BEGIN;
DROP TABLE public.diff_drop_group_parent,diff_drop_group_child,diff_drop_group_survivor;
ROLLBACK;
SELECT id FROM diff_drop_group_parent;
SELECT id,pid FROM diff_drop_group_child;
SELECT id,pid FROM diff_drop_group_survivor;
INSERT INTO diff_drop_group_child VALUES(4,99);
DROP TABLE diff_drop_group_child,diff_drop_group_parent;
SELECT id FROM diff_drop_group_parent;
SELECT id,pid FROM diff_drop_group_child;
SELECT id,pid FROM diff_drop_group_survivor;
INSERT INTO diff_drop_group_survivor VALUES(4,99);
DROP TABLE diff_drop_group_parent,diff_drop_group_child CASCADE;
SELECT id,pid FROM diff_drop_group_survivor;
INSERT INTO diff_drop_group_survivor VALUES(4,99);
DROP TABLE diff_drop_group_survivor;
CREATE TABLE diff_drop_cycle_a(id INT PRIMARY KEY,bid INT);
CREATE TABLE diff_drop_cycle_b(id INT PRIMARY KEY,aid INT REFERENCES diff_drop_cycle_a(id));
ALTER TABLE diff_drop_cycle_a ADD CONSTRAINT diff_drop_cycle_a_fkey FOREIGN KEY(bid) REFERENCES diff_drop_cycle_b(id);
DROP TABLE diff_drop_cycle_a,public.diff_drop_cycle_b;
SELECT id FROM diff_drop_cycle_a;
SELECT id FROM diff_drop_cycle_b;
