DROP TABLE IF EXISTS public.diff_dsfd_child;
DROP SCHEMA IF EXISTS diff_dsfd CASCADE;
CREATE SCHEMA diff_dsfd;
CREATE TABLE diff_dsfd.parent (id integer PRIMARY KEY);
SET search_path TO diff_dsfd, public;
CREATE TABLE public.diff_dsfd_child (id integer REFERENCES parent(id));
SET search_path TO public;
INSERT INTO diff_dsfd.parent VALUES (1);
INSERT INTO public.diff_dsfd_child VALUES (1);
DROP SCHEMA diff_dsfd;
SELECT id FROM diff_dsfd.parent;
BEGIN;
DROP SCHEMA diff_dsfd CASCADE;
INSERT INTO public.diff_dsfd_child VALUES (2);
ROLLBACK;
SELECT id FROM diff_dsfd.parent;
SELECT id FROM public.diff_dsfd_child ORDER BY id;
DROP SCHEMA diff_dsfd CASCADE;
INSERT INTO public.diff_dsfd_child VALUES (3);
SELECT id FROM public.diff_dsfd_child ORDER BY id;
