DROP SCHEMA IF EXISTS diff_idx_first CASCADE;
DROP SCHEMA IF EXISTS diff_idx_second CASCADE;
CREATE SCHEMA diff_idx_first;
CREATE SCHEMA diff_idx_second;
CREATE TABLE diff_idx_first.items (id integer);
CREATE TABLE diff_idx_second.items (id integer);
INSERT INTO diff_idx_first.items VALUES (51);
INSERT INTO diff_idx_second.items VALUES (52);
CREATE INDEX diff_shadow_idx ON diff_idx_first.items (id);
CREATE INDEX diff_shadow_idx ON diff_idx_second.items (id);
SET search_path TO diff_idx_second, diff_idx_first, public;
DROP INDEX diff_shadow_idx;
DROP INDEX diff_idx_first.diff_shadow_idx;
SELECT id FROM diff_idx_first.items;
SELECT id FROM diff_idx_second.items;
SET search_path TO public;
DROP TABLE diff_idx_first.items;
DROP TABLE diff_idx_second.items;
DROP SCHEMA diff_idx_first;
DROP SCHEMA diff_idx_second;
