DROP TABLE IF EXISTS public.diff_dfsp_child;
DROP TABLE IF EXISTS public.diff_dfsp_parent;
DROP SCHEMA IF EXISTS diff_dfsp_shadow CASCADE;
CREATE TABLE public.diff_dfsp_parent (id integer PRIMARY KEY);
CREATE TABLE public.diff_dfsp_child (id integer REFERENCES diff_dfsp_parent(id));
INSERT INTO public.diff_dfsp_parent VALUES (1);
CREATE SCHEMA diff_dfsp_shadow;
CREATE TABLE diff_dfsp_shadow.diff_dfsp_parent (id integer PRIMARY KEY);
INSERT INTO diff_dfsp_shadow.diff_dfsp_parent VALUES (2);
CREATE TABLE diff_dfsp_shadow.diff_dfsp_alter_child (id integer);
SET search_path TO diff_dfsp_shadow, public;
ALTER TABLE diff_dfsp_alter_child ADD CONSTRAINT diff_dfsp_alter_fkey FOREIGN KEY (id) REFERENCES diff_dfsp_parent(id);
INSERT INTO diff_dfsp_alter_child VALUES (2);
DROP TABLE public.diff_dfsp_parent;
SET search_path TO public;
DROP TABLE diff_dfsp_shadow.diff_dfsp_parent;
SELECT id FROM public.diff_dfsp_parent;
INSERT INTO public.diff_dfsp_child VALUES (1);
SELECT id FROM public.diff_dfsp_child;
SELECT id FROM diff_dfsp_shadow.diff_dfsp_alter_child;
