DROP TABLE IF EXISTS diff_dfct_child;
DROP TABLE IF EXISTS diff_dfct_child_named;
DROP TABLE IF EXISTS diff_dfct_parent;
CREATE TABLE diff_dfct_parent (id integer PRIMARY KEY);
CREATE TABLE diff_dfct_child (id integer REFERENCES diff_dfct_parent(id));
CREATE TABLE diff_dfct_child_named (id integer, CONSTRAINT diff_dfct_named_fkey FOREIGN KEY (id) REFERENCES diff_dfct_parent(id));
INSERT INTO diff_dfct_parent VALUES (1);
INSERT INTO diff_dfct_child VALUES (1);
INSERT INTO diff_dfct_child_named VALUES (1);
BEGIN;
DROP TABLE diff_dfct_parent CASCADE;
INSERT INTO diff_dfct_child VALUES (2);
INSERT INTO diff_dfct_child_named VALUES (2);
ROLLBACK;
SELECT id FROM diff_dfct_parent;
SELECT id FROM diff_dfct_child ORDER BY id;
SELECT id FROM diff_dfct_child_named ORDER BY id;
BEGIN;
DROP TABLE diff_dfct_parent CASCADE;
COMMIT;
INSERT INTO diff_dfct_child VALUES (3);
INSERT INTO diff_dfct_child_named VALUES (3);
SELECT id FROM diff_dfct_child ORDER BY id;
SELECT id FROM diff_dfct_child_named ORDER BY id;
