CREATE TABLE diff_drop_multiple_a(id INT);
CREATE TABLE diff_drop_multiple_b(id INT);
DROP TABLE diff_drop_multiple_a,diff_drop_multiple_b;
CREATE TABLE diff_drop_multiple_a(id INT);
CREATE TABLE diff_drop_multiple_b(id INT);
DROP TABLE diff_drop_multiple_a;
DROP TABLE diff_drop_multiple_b;
CREATE TABLE diff_drop_multiple_c(id INT);
CREATE TABLE diff_drop_multiple_d(id INT);
INSERT INTO diff_drop_multiple_c VALUES(3);
INSERT INTO diff_drop_multiple_d VALUES(4);
DROP TABLE diff_drop_multiple_c,diff_drop_multiple_missing;
SELECT id FROM diff_drop_multiple_c;
SELECT id FROM diff_drop_multiple_d;
BEGIN;
SAVEPOINT diff_drop_multiple_sp;
DROP TABLE diff_drop_multiple_c,diff_drop_multiple_missing;
ROLLBACK TO SAVEPOINT diff_drop_multiple_sp;
SELECT id FROM diff_drop_multiple_c;
DROP TABLE diff_drop_multiple_c,diff_drop_multiple_d;
ROLLBACK;
SELECT id FROM diff_drop_multiple_c;
SELECT id FROM diff_drop_multiple_d;
DROP TABLE diff_drop_multiple_c,diff_drop_multiple_c,public.diff_drop_multiple_d;
CREATE TABLE "diff_drop,comma_a"(id INT);
CREATE TABLE "diff_drop,comma_b"(id INT);
DROP TABLE "diff_drop,comma_a","diff_drop,comma_b";
CREATE TABLE diff_drop_multiple_shadow(id INT);
INSERT INTO diff_drop_multiple_shadow VALUES(9);
CREATE TEMP TABLE diff_drop_multiple_shadow(id INT);
CREATE TEMP TABLE diff_drop_multiple_temp_b(id INT);
INSERT INTO diff_drop_multiple_shadow VALUES(7);
DROP TABLE diff_drop_multiple_shadow,diff_drop_multiple_missing;
SELECT id FROM diff_drop_multiple_shadow;
SELECT id FROM public.diff_drop_multiple_shadow;
DROP TABLE IF EXISTS diff_drop_multiple_missing,diff_drop_multiple_shadow,diff_drop_multiple_temp_b;
SELECT id FROM diff_drop_multiple_shadow;
DROP TABLE diff_drop_multiple_shadow;
CREATE SEQUENCE diff_drop_multiple_owned_seq;
CREATE TABLE diff_drop_multiple_owned(id INT DEFAULT nextval('diff_drop_multiple_owned_seq') PRIMARY KEY,code TEXT);
ALTER SEQUENCE diff_drop_multiple_owned_seq OWNED BY diff_drop_multiple_owned.id;
INSERT INTO diff_drop_multiple_owned(code) VALUES('kept');
SELECT currval('diff_drop_multiple_owned_seq');
DROP TABLE diff_drop_multiple_owned,diff_drop_multiple_missing;
SELECT id,code FROM diff_drop_multiple_owned;
SELECT currval('diff_drop_multiple_owned_seq');
INSERT INTO diff_drop_multiple_owned(code) VALUES('next') RETURNING id;
DROP TABLE diff_drop_multiple_owned;
