DROP TABLE IF EXISTS diff_expression_null_values;
CREATE TABLE diff_expression_null_values(id INT,f INT,t TEXT);
INSERT INTO diff_expression_null_values VALUES (1,0,''),(2,1,'NULL'),(3,NULL,NULL);
SELECT count(*) FILTER (WHERE abs(f) IS NULL) FROM diff_expression_null_values;
SELECT count(*) FILTER (WHERE abs(f) IS NOT NULL) FROM diff_expression_null_values;
SELECT count(*) FILTER (WHERE (f=0) IS NULL) FROM diff_expression_null_values;
SELECT count(*) FILTER (WHERE (f=0) IS NOT NULL) FROM diff_expression_null_values;
SELECT id,t FROM diff_expression_null_values WHERE abs(f) IS NULL ORDER BY id;
SELECT id,t FROM diff_expression_null_values WHERE (f=0) IS NULL ORDER BY id;
SELECT id,t FROM diff_expression_null_values WHERE abs(f) IS NOT NULL AND id=1 ORDER BY id;
SELECT count(*) FILTER (WHERE coalesce(f,0) IS NOT NULL) FROM diff_expression_null_values;
SELECT count(*) FILTER (WHERE length(t) IS NULL) FROM diff_expression_null_values;
DROP TABLE diff_expression_null_values;
DROP TABLE IF EXISTS diff_expression_null_virtual;
CREATE TABLE diff_expression_null_virtual(id INT,f INT,g INT GENERATED ALWAYS AS (f+1) VIRTUAL);
INSERT INTO diff_expression_null_virtual(id,f) VALUES (1,0),(2,1),(3,NULL);
SELECT id,g FROM diff_expression_null_virtual WHERE g IS NULL ORDER BY id;
SELECT id,g FROM diff_expression_null_virtual WHERE g IS NOT NULL ORDER BY id;
DROP TABLE diff_expression_null_virtual;
