CREATE TABLE diff_fk_empty_parent(id INT PRIMARY KEY,code TEXT UNIQUE);
CREATE TABLE diff_fk_empty_child(id INT PRIMARY KEY,code TEXT REFERENCES diff_fk_empty_parent(code));
INSERT INTO diff_fk_empty_parent VALUES(1,'kept'),(2,NULL);
INSERT INTO diff_fk_empty_child VALUES(10,'kept');
UPDATE diff_fk_empty_child SET code='' WHERE id=10;
SELECT id,code FROM diff_fk_empty_child;
INSERT INTO diff_fk_empty_parent VALUES(3,'');
UPDATE diff_fk_empty_child SET code='' WHERE id=10;
SELECT id,code FROM diff_fk_empty_child;
UPDATE diff_fk_empty_child SET code=NULL WHERE id=10;
SELECT id,code FROM diff_fk_empty_child;
DELETE FROM diff_fk_empty_parent WHERE id=3;
UPDATE diff_fk_empty_child SET code='' WHERE id=10;
SELECT id,code FROM diff_fk_empty_child;
INSERT INTO diff_fk_empty_child VALUES(20,'');
SELECT id,code FROM diff_fk_empty_child ORDER BY id;
DROP TABLE diff_fk_empty_parent,diff_fk_empty_child;
CREATE TABLE diff_fk_empty_deferred_parent(id INT PRIMARY KEY,code TEXT UNIQUE);
CREATE TABLE diff_fk_empty_deferred_child(id INT PRIMARY KEY,code TEXT,CONSTRAINT empty_deferred_fk FOREIGN KEY(code) REFERENCES diff_fk_empty_deferred_parent(code) DEFERRABLE INITIALLY DEFERRED);
INSERT INTO diff_fk_empty_deferred_parent VALUES(1,'kept'),(2,NULL);
INSERT INTO diff_fk_empty_deferred_child VALUES(10,'kept');
BEGIN;
UPDATE diff_fk_empty_deferred_child SET code='' WHERE id=10;
COMMIT;
SELECT id,code FROM diff_fk_empty_deferred_child;
BEGIN;
INSERT INTO diff_fk_empty_deferred_child VALUES(20,'');
COMMIT;
SELECT id,code FROM diff_fk_empty_deferred_child ORDER BY id;
BEGIN;
UPDATE diff_fk_empty_deferred_child SET code=NULL WHERE id=10;
COMMIT;
SELECT id,code FROM diff_fk_empty_deferred_child;
DROP TABLE diff_fk_empty_deferred_parent,diff_fk_empty_deferred_child;
CREATE TABLE diff_fk_empty_pair_parent(a TEXT,b INT,UNIQUE(a,b));
CREATE TABLE diff_fk_empty_pair_child(id INT PRIMARY KEY,a TEXT,b INT,FOREIGN KEY(a,b) REFERENCES diff_fk_empty_pair_parent(a,b));
INSERT INTO diff_fk_empty_pair_parent VALUES(NULL,7);
INSERT INTO diff_fk_empty_pair_child VALUES(1,NULL,7),(2,'',NULL);
INSERT INTO diff_fk_empty_pair_child VALUES(3,'',7);
UPDATE diff_fk_empty_pair_child SET a='' WHERE id=1;
UPDATE diff_fk_empty_pair_child SET b=7 WHERE id=2;
SELECT id,a,b FROM diff_fk_empty_pair_child ORDER BY id;
INSERT INTO diff_fk_empty_pair_parent VALUES('',7);
UPDATE diff_fk_empty_pair_child SET a='',b=7;
SELECT id,a,b FROM diff_fk_empty_pair_child ORDER BY id;
DROP TABLE diff_fk_empty_pair_parent,diff_fk_empty_pair_child;
CREATE TABLE diff_fk_empty_self(id INT PRIMARY KEY,code TEXT UNIQUE,parent_code TEXT REFERENCES diff_fk_empty_self(code));
INSERT INTO diff_fk_empty_self(id) VALUES(1);
UPDATE diff_fk_empty_self SET parent_code='' WHERE id=1;
SELECT code,parent_code FROM diff_fk_empty_self;
UPDATE diff_fk_empty_self SET code='',parent_code='' WHERE id=1;
SELECT code,parent_code FROM diff_fk_empty_self;
DROP TABLE diff_fk_empty_self;
CREATE TABLE diff_fk_empty_final_parent(id INT PRIMARY KEY,code TEXT UNIQUE);
CREATE TABLE diff_fk_empty_final_child(id INT PRIMARY KEY,code TEXT,CONSTRAINT final_empty_fk FOREIGN KEY(code) REFERENCES diff_fk_empty_final_parent(code) DEFERRABLE INITIALLY DEFERRED);
INSERT INTO diff_fk_empty_final_parent VALUES(1,'kept'),(2,NULL);
INSERT INTO diff_fk_empty_final_child VALUES(10,'kept');
BEGIN;
SAVEPOINT empty_sp;
UPDATE diff_fk_empty_final_child SET code='' WHERE id=10;
SET CONSTRAINTS final_empty_fk IMMEDIATE;
ROLLBACK TO SAVEPOINT empty_sp;
SELECT id,code FROM diff_fk_empty_final_child;
COMMIT;
BEGIN;
UPDATE diff_fk_empty_final_child SET code='' WHERE id=10;
UPDATE diff_fk_empty_final_child SET code=NULL WHERE id=10;
COMMIT;
SELECT id,code FROM diff_fk_empty_final_child;
BEGIN;
INSERT INTO diff_fk_empty_final_child VALUES(20,'');
INSERT INTO diff_fk_empty_final_parent VALUES(3,'');
COMMIT;
SELECT id,code FROM diff_fk_empty_final_child ORDER BY id;
BEGIN;
DELETE FROM diff_fk_empty_final_child WHERE id=20;
DELETE FROM diff_fk_empty_final_parent WHERE id=3;
INSERT INTO diff_fk_empty_final_child VALUES(30,'');
DELETE FROM diff_fk_empty_final_child WHERE id=30;
COMMIT;
SELECT id,code FROM diff_fk_empty_final_child;
DROP TABLE diff_fk_empty_final_parent,diff_fk_empty_final_child;
