CREATE TABLE diff_fk_statement_unique(id INT PRIMARY KEY,code TEXT UNIQUE,parent_code TEXT REFERENCES diff_fk_statement_unique(code));
INSERT INTO diff_fk_statement_unique VALUES(1,'first',NULL),(2,'second','first');
SELECT id,code,parent_code FROM diff_fk_statement_unique ORDER BY id;
DROP TABLE diff_fk_statement_unique;
CREATE TABLE diff_fk_statement_forward(id INT PRIMARY KEY,pid INT REFERENCES diff_fk_statement_forward(id));
INSERT INTO diff_fk_statement_forward VALUES(1,2),(2,NULL);
SELECT id,pid FROM diff_fk_statement_forward ORDER BY id;
DROP TABLE diff_fk_statement_forward;
CREATE TABLE diff_fk_statement_pair(id INT PRIMARY KEY,a INT,b TEXT,pa INT,pb TEXT,UNIQUE(a,b),FOREIGN KEY(pa,pb) REFERENCES diff_fk_statement_pair(a,b));
INSERT INTO diff_fk_statement_pair VALUES(1,7,'first',NULL,NULL),(2,8,'other',7,'first');
SELECT id,a,b,pa,pb FROM diff_fk_statement_pair ORDER BY id;
DROP TABLE diff_fk_statement_pair;
CREATE TABLE diff_fk_statement_cycle(id INT PRIMARY KEY,pid INT REFERENCES diff_fk_statement_cycle(id));
INSERT INTO diff_fk_statement_cycle VALUES(1,2),(2,1);
INSERT INTO diff_fk_statement_cycle VALUES(3,4),(4,999);
SELECT id,pid FROM diff_fk_statement_cycle ORDER BY id;
BEGIN;
SAVEPOINT fk_statement_sp;
INSERT INTO diff_fk_statement_cycle VALUES(3,4),(4,999);
ROLLBACK TO SAVEPOINT fk_statement_sp;
SELECT id,pid FROM diff_fk_statement_cycle ORDER BY id;
COMMIT;
DROP TABLE diff_fk_statement_cycle;
CREATE TABLE diff_fk_statement_char(id INT PRIMARY KEY,code CHAR(4) UNIQUE,parent_code CHAR(2) REFERENCES diff_fk_statement_char(code));
INSERT INTO diff_fk_statement_char VALUES(1,'aa',NULL),(2,'bb','aa');
SELECT id,code,parent_code FROM diff_fk_statement_char ORDER BY id;
DROP TABLE diff_fk_statement_char;
CREATE TABLE diff_fk_statement_char_pk(code CHAR(4) PRIMARY KEY,parent_code CHAR(2) REFERENCES diff_fk_statement_char_pk(code));
INSERT INTO diff_fk_statement_char_pk VALUES('aa',NULL),('bb','aa');
SELECT code,parent_code FROM diff_fk_statement_char_pk ORDER BY code;
DROP TABLE diff_fk_statement_char_pk;
CREATE TABLE diff_fk_statement_long_pk(code TEXT PRIMARY KEY,parent_code TEXT REFERENCES diff_fk_statement_long_pk(code));
INSERT INTO diff_fk_statement_long_pk VALUES('12345678901234567890first',NULL),('child','12345678901234567890other');
SELECT code,parent_code FROM diff_fk_statement_long_pk;
DROP TABLE diff_fk_statement_long_pk;
