CREATE TABLE diff_fk_modify_parent(id INT PRIMARY KEY);
CREATE TABLE diff_fk_modify_child(id INT PRIMARY KEY,pid INT REFERENCES diff_fk_modify_parent(id));
INSERT INTO diff_fk_modify_parent VALUES(1),(2);
INSERT INTO diff_fk_modify_child VALUES(10,1),(20,2);
UPDATE diff_fk_modify_child SET pid=77 WHERE id=10;
UPDATE diff_fk_modify_parent SET id=3 WHERE id=1;
DELETE FROM diff_fk_modify_parent WHERE id=1;
SELECT id,pid FROM diff_fk_modify_child ORDER BY id;
SELECT id FROM diff_fk_modify_parent ORDER BY id;
BEGIN;
SAVEPOINT fk_modify_sp;
UPDATE diff_fk_modify_child SET pid=78 WHERE id=20;
SELECT id FROM diff_fk_modify_child;
ROLLBACK TO SAVEPOINT fk_modify_sp;
SELECT id,pid FROM diff_fk_modify_child ORDER BY id;
COMMIT;
CREATE TABLE diff_fk_modify_unique(id INT PRIMARY KEY,code TEXT UNIQUE);
CREATE TABLE diff_fk_modify_unique_child(id INT PRIMARY KEY,code TEXT REFERENCES diff_fk_modify_unique(code));
INSERT INTO diff_fk_modify_unique VALUES(1,'kept');
INSERT INTO diff_fk_modify_unique_child VALUES(2,'kept');
UPDATE diff_fk_modify_unique_child SET code='absent' WHERE id=2;
UPDATE diff_fk_modify_unique SET code='new' WHERE id=1;
DELETE FROM diff_fk_modify_unique WHERE id=1;
SELECT code FROM diff_fk_modify_unique;
SELECT code FROM diff_fk_modify_unique_child;
DROP TABLE diff_fk_modify_parent,diff_fk_modify_child,diff_fk_modify_unique,diff_fk_modify_unique_child;
CREATE TABLE diff_fk_modify_pair(a INT,b INT,PRIMARY KEY(a,b));
CREATE TABLE diff_fk_modify_pair_child(id INT PRIMARY KEY,x INT,y INT,FOREIGN KEY(x,y) REFERENCES diff_fk_modify_pair(a,b));
INSERT INTO diff_fk_modify_pair VALUES(1,2);
INSERT INTO diff_fk_modify_pair_child VALUES(10,1,2);
UPDATE diff_fk_modify_pair_child SET y=3 WHERE id=10;
UPDATE diff_fk_modify_pair SET b=3 WHERE a=1;
DELETE FROM diff_fk_modify_pair WHERE a=1;
SELECT id,x,y FROM diff_fk_modify_pair_child;
SELECT a,b FROM diff_fk_modify_pair;
DROP TABLE diff_fk_modify_pair,diff_fk_modify_pair_child;
