CREATE TABLE diff_fk_ins_parent(id INT PRIMARY KEY,code INT UNIQUE,g INT,UNIQUE(code,g));
INSERT INTO diff_fk_ins_parent VALUES(7,9,11);
CREATE TABLE diff_fk_ins_pk(id INT PRIMARY KEY,pid INT REFERENCES diff_fk_ins_parent(id));
CREATE TABLE diff_fk_ins_unique(id INT PRIMARY KEY,code INT REFERENCES diff_fk_ins_parent(code));
CREATE TABLE diff_fk_ins_pair(id INT PRIMARY KEY,code INT,g INT,FOREIGN KEY(code,g) REFERENCES diff_fk_ins_parent(code,g));
INSERT INTO diff_fk_ins_pk VALUES(1,99) RETURNING id;
INSERT INTO diff_fk_ins_unique VALUES(1,7);
INSERT INTO diff_fk_ins_pair VALUES(1,9,12);
SELECT id FROM diff_fk_ins_pk;
SELECT id FROM diff_fk_ins_unique;
SELECT id FROM diff_fk_ins_pair;
INSERT INTO diff_fk_ins_pk VALUES(1,7);
INSERT INTO diff_fk_ins_unique VALUES(1,9);
INSERT INTO diff_fk_ins_pair VALUES(1,9,11);
INSERT INTO diff_fk_ins_pk VALUES(2,7),(3,99);
SELECT id,pid FROM diff_fk_ins_pk ORDER BY id;
INSERT INTO diff_fk_ins_pk SELECT 4,99 FROM diff_fk_ins_parent;
SELECT id,pid FROM diff_fk_ins_pk ORDER BY id;
BEGIN;
SAVEPOINT diff_fk_ins_sp;
INSERT INTO diff_fk_ins_unique VALUES(2,7);
SELECT id FROM diff_fk_ins_unique;
ROLLBACK TO SAVEPOINT diff_fk_ins_sp;
SELECT id,code FROM diff_fk_ins_unique;
COMMIT;
INSERT INTO diff_fk_ins_pair VALUES(2,NULL,99);
SELECT id,code,g FROM diff_fk_ins_pair ORDER BY id;
DROP TABLE diff_fk_ins_pair;
DROP TABLE diff_fk_ins_unique;
DROP TABLE diff_fk_ins_pk;
DROP TABLE diff_fk_ins_parent;
