CREATE SCHEMA "self definition schema";
CREATE TABLE "self definition schema"."self.node"("key id" INT PRIMARY KEY,"parent id" INT REFERENCES "self definition schema"."self.node"("key id"));
INSERT INTO "self definition schema"."self.node"("key id") VALUES(1);
UPDATE "self definition schema"."self.node" SET "parent id"=1;
SELECT "key id","parent id" FROM "self definition schema"."self.node";
DROP TABLE "self definition schema"."self.node";
DROP SCHEMA "self definition schema";
CREATE SCHEMA "quoted constraint schema";
CREATE TABLE "quoted constraint schema"."p""arent"("parent id" INT,"a key" INT,"b""key" TEXT,PRIMARY KEY("parent id"),CONSTRAINT pair_key UNIQUE("a key","b""key"));
INSERT INTO "quoted constraint schema"."p""arent" VALUES(1,7,'value');
CREATE TABLE diff_quoted_constraint_child("child id" INT PRIMARY KEY,"parent key" INT REFERENCES "quoted constraint schema"."p""arent"("parent id"),"a key" INT,"b""key" TEXT);
INSERT INTO diff_quoted_constraint_child VALUES(1,1,7,'value');
INSERT INTO diff_quoted_constraint_child VALUES(2,99,NULL,NULL);
SELECT "child id","parent key" FROM diff_quoted_constraint_child;
ALTER TABLE diff_quoted_constraint_child ADD CONSTRAINT pair_fk FOREIGN KEY("a key","b""key") REFERENCES "quoted constraint schema"."p""arent"("a key","b""key");
INSERT INTO diff_quoted_constraint_child VALUES(2,1,7,'missing');
UPDATE diff_quoted_constraint_child SET "b""key"='missing';
SELECT "child id","a key","b""key" FROM diff_quoted_constraint_child;
BEGIN;
SAVEPOINT quoted_constraint_sp;
ALTER TABLE diff_quoted_constraint_child DROP CONSTRAINT pair_fk;
ROLLBACK TO SAVEPOINT quoted_constraint_sp;
COMMIT;
UPDATE diff_quoted_constraint_child SET "b""key"='missing';
SELECT "child id","a key","b""key" FROM diff_quoted_constraint_child;
DROP TABLE diff_quoted_constraint_child;
DROP TABLE "quoted constraint schema"."p""arent";
DROP SCHEMA "quoted constraint schema";
CREATE TABLE diff_folded_constraint(ID INT,VALUE TEXT,PRIMARY KEY(ID),UNIQUE(VALUE));
INSERT INTO diff_folded_constraint VALUES(1,'value');
CREATE TABLE diff_folded_reference(ID INT PRIMARY KEY,PID INT,FOREIGN KEY(PID) REFERENCES DIFF_FOLDED_CONSTRAINT(ID));
INSERT INTO diff_folded_reference VALUES(1,1);
SELECT id,pid FROM diff_folded_reference;
DROP TABLE diff_folded_constraint,diff_folded_reference;
