CREATE TABLE diff_fk_self_insert(id INT PRIMARY KEY,pid INT REFERENCES diff_fk_self_insert(id));
INSERT INTO diff_fk_self_insert VALUES(1,1);
SELECT id,pid FROM diff_fk_self_insert;
INSERT INTO diff_fk_self_insert VALUES(2,999);
INSERT INTO diff_fk_self_insert VALUES(2,2);
INSERT INTO diff_fk_self_insert VALUES(3,3),(4,4);
INSERT INTO diff_fk_self_insert VALUES(5,5),(6,999);
SELECT id,pid FROM diff_fk_self_insert ORDER BY id;
INSERT INTO diff_fk_self_insert VALUES(1,1);
SELECT id,pid FROM diff_fk_self_insert ORDER BY id;
DROP TABLE diff_fk_self_insert;
CREATE TABLE diff_fk_insert_self_unique(id INT PRIMARY KEY,code TEXT UNIQUE,parent_code TEXT REFERENCES diff_fk_insert_self_unique(code));
INSERT INTO diff_fk_insert_self_unique VALUES(1,'own','own');
INSERT INTO diff_fk_insert_self_unique VALUES(2,'','');
INSERT INTO diff_fk_insert_self_unique VALUES(3,NULL,'');
INSERT INTO diff_fk_insert_self_unique VALUES(4,NULL,'missing');
INSERT INTO diff_fk_insert_self_unique VALUES(4,NULL,NULL);
SELECT id,code,parent_code FROM diff_fk_insert_self_unique ORDER BY id;
DROP TABLE diff_fk_insert_self_unique;
CREATE TABLE diff_fk_insert_self_pair(id INT PRIMARY KEY,a INT,b TEXT,pa INT,pb TEXT,UNIQUE(a,b),FOREIGN KEY(pa,pb) REFERENCES diff_fk_insert_self_pair(a,b));
INSERT INTO diff_fk_insert_self_pair VALUES(1,7,'',7,'');
INSERT INTO diff_fk_insert_self_pair VALUES(2,8,'other',7,'');
INSERT INTO diff_fk_insert_self_pair VALUES(3,9,'third',9,'missing');
INSERT INTO diff_fk_insert_self_pair VALUES(3,9,'third',NULL,'missing');
SELECT id,a,b,pa,pb FROM diff_fk_insert_self_pair ORDER BY id;
DROP TABLE diff_fk_insert_self_pair;
CREATE TABLE diff_fk_insert_self_default(id INT PRIMARY KEY,code TEXT DEFAULT 'default' UNIQUE,parent_code TEXT DEFAULT 'default' REFERENCES diff_fk_insert_self_default(code));
INSERT INTO diff_fk_insert_self_default(id) VALUES(1) RETURNING code,parent_code;
DROP TABLE diff_fk_insert_self_default;
CREATE SCHEMA "self insert schema";
CREATE TABLE "self insert schema"."self.node"("key id" INT PRIMARY KEY,"parent id" INT REFERENCES "self insert schema"."self.node"("key id"));
INSERT INTO "self insert schema"."self.node" VALUES(1,1) RETURNING "key id","parent id";
SELECT "key id","parent id" FROM "self insert schema"."self.node";
DROP TABLE "self insert schema"."self.node";
DROP SCHEMA "self insert schema";
