SELECT 1 WHERE true;
SELECT 1 WHERE false;
SELECT 1 WHERE NULL;
SELECT 1 WHERE true AND false;
SELECT 1 WHERE NOT false;
SELECT 1 WHERE 1 = 1 AND false;
SELECT 1 WHERE 1 = 2 OR true;
SELECT 1 WHERE 1;
