DROP TABLE IF EXISTS diff_icdt;
CREATE TABLE diff_icdt (id integer, v integer);
INSERT INTO diff_icdt VALUES (1, 10), (2, 20);
BEGIN;
CREATE INDEX diff_icdt_v_idx ON diff_icdt (v);
SELECT id FROM diff_icdt WHERE v = 20;
ROLLBACK;
CREATE INDEX diff_icdt_v_idx ON diff_icdt (v);
BEGIN;
DROP INDEX diff_icdt_v_idx;
SELECT id FROM diff_icdt WHERE v = 20;
ROLLBACK;
SELECT id FROM diff_icdt WHERE v = 10;
BEGIN;
SAVEPOINT drop_index_point;
DROP INDEX diff_icdt_v_idx;
ROLLBACK TO SAVEPOINT drop_index_point;
SELECT id FROM diff_icdt WHERE v = 20;
COMMIT;
DROP INDEX diff_icdt_v_idx;
