CREATE TABLE diff_insert_null_source(id INT,pid INT,content TEXT);
CREATE TABLE diff_insert_null_target(id INT PRIMARY KEY,pid INT,content TEXT DEFAULT 'fallback');
INSERT INTO diff_insert_null_source VALUES(1,2,'NULL'),(2,NULL,NULL),(3,NULL,'');
INSERT INTO diff_insert_null_target SELECT id,pid,content FROM diff_insert_null_source RETURNING id,pid,content;
SELECT id,pid,content FROM diff_insert_null_target ORDER BY id;
CREATE TABLE diff_insert_null_star(id INT,pid INT,content TEXT);
INSERT INTO diff_insert_null_star SELECT * FROM diff_insert_null_source RETURNING id,pid,content;
CREATE TABLE diff_insert_null_projected(id INT,pid INT,content TEXT);
INSERT INTO diff_insert_null_projected SELECT id+10,pid*2,upper(content) FROM diff_insert_null_source WHERE pid IS NULL RETURNING id,pid,content;
INSERT INTO diff_insert_null_projected SELECT id+20,pid,content FROM diff_insert_null_source WHERE content='' RETURNING id,pid,content;
INSERT INTO diff_insert_null_projected SELECT 30,NULL,'NULL' RETURNING pid,content;
CREATE TABLE diff_insert_nonnull_target(id INT,pid INT NOT NULL,content TEXT);
INSERT INTO diff_insert_nonnull_target SELECT id,pid,content FROM diff_insert_null_source;
SELECT id FROM diff_insert_nonnull_target;
BEGIN;
SAVEPOINT insert_null_sp;
INSERT INTO diff_insert_nonnull_target SELECT id,pid,content FROM diff_insert_null_source;
ROLLBACK TO SAVEPOINT insert_null_sp;
SELECT id FROM diff_insert_nonnull_target;
COMMIT;
DROP TABLE diff_insert_null_target,diff_insert_null_star,diff_insert_null_projected,diff_insert_nonnull_target,diff_insert_null_source;
