CREATE TABLE key_write_single (id BIGINT PRIMARY KEY,value BIGINT);
CREATE INDEX key_write_value ON key_write_single(value);
INSERT INTO key_write_single VALUES ('0001','+0007');
SELECT id FROM key_write_single WHERE id=1;
INSERT INTO key_write_single VALUES (1,7);
INSERT INTO key_write_single VALUES ('-0','0000');
INSERT INTO key_write_single VALUES (0,0);
SELECT id,value FROM key_write_single ORDER BY id;
BEGIN;
UPDATE key_write_single SET value='+0008' WHERE id=1;
SELECT id FROM key_write_single WHERE value=8;
ROLLBACK;
SELECT id,value FROM key_write_single ORDER BY id;
REINDEX TABLE key_write_single;
SELECT id FROM key_write_single WHERE id=1;
CREATE TABLE key_write_pair (a BIGINT,b BIGINT,PRIMARY KEY(a,b));
INSERT INTO key_write_pair VALUES ('+0001','0002');
INSERT INTO key_write_pair VALUES (1,2);
SELECT a,b FROM key_write_pair;
DROP TABLE key_write_single;
DROP TABLE key_write_pair;
