-- NULL semantics: literals, coalesce, nullif, greatest/least, bool aggregates
SELECT coalesce(NULL, NULL, 7)
SELECT nullif(5, 5), nullif(5, 6)
SELECT greatest(1, 3), least(4, 2)
SELECT NULL::text IS NULL
SELECT 1 + NULL
SELECT 'a' || NULL
SELECT NULL AND true, NULL OR true, NULL AND false, NULL OR false
SELECT NOT NULL
SELECT NULL IS NULL, NULL IS NOT NULL, 3 IS NULL
SELECT NULLIF(NULL, 1) IS NULL
SELECT NULL = NULL IS NULL, (NULL = NULL) IS NULL, 1 = 1 IS NULL
SELECT 2 + 3 IS NULL
DROP TABLE IF EXISTS nt2
CREATE TABLE nt2 (id INT, v INT)
INSERT INTO nt2 VALUES (1, 10), (2, 8), (3, 30)
SELECT bool_and(v > 5) FROM nt2
SELECT bool_or(v > 25) FROM nt2
SELECT every(v > 1) FROM nt2
SELECT bool_and(v > 9) FROM nt2
DROP TABLE nt2

-- WHERE-path IS [NOT] NULL on parenthesized expressions
DROP TABLE IF EXISTS nt3
CREATE TABLE nt3 (id INT, v INT)
INSERT INTO nt3 VALUES (1, 5), (2, 9)
SELECT id FROM nt3 WHERE (v > 5) IS NULL
SELECT id FROM nt3 WHERE (v > 5) IS NOT NULL
SELECT id FROM nt3 WHERE v > 5 IS NULL
SELECT id FROM nt3 WHERE v IS NOT NULL
SELECT id FROM nt3 WHERE (v > 5) AND id IS NOT NULL
DROP TABLE nt3

-- stored NULL (physical) semantics
DROP TABLE IF EXISTS nt10
CREATE TABLE nt10 (id INT, v INT)
INSERT INTO nt10 VALUES (1, 10), (2, NULL), (3, 30)
SELECT * FROM nt10
SELECT count(v) FROM nt10
SELECT sum(v), min(v), max(v), avg(v) FROM nt10
SELECT id FROM nt10 WHERE v IS NULL
SELECT id FROM nt10 WHERE v IS NOT NULL ORDER BY id
SELECT id, v + 1 FROM nt10 ORDER BY id
SELECT id, v::text FROM nt10 ORDER BY id
DROP TABLE nt10