-- NULL comparison and three-valued logic
SELECT NULL = NULL
SELECT 1 = NULL
SELECT NULL AND true
SELECT NULL OR true
SELECT NULL IS DISTINCT FROM NULL
SELECT 1 IS DISTINCT FROM NULL
SELECT COALESCE(NULL, NULL, 3)
SELECT NULLIF(1, 1)
