CREATE TABLE diff_numeric_primary (v NUMERIC PRIMARY KEY);
INSERT INTO diff_numeric_primary VALUES (0.50);
INSERT INTO diff_numeric_primary VALUES (0.500);
SELECT v FROM diff_numeric_primary;
INSERT INTO diff_numeric_primary VALUES (1.00),(1.000);
SELECT v FROM diff_numeric_primary;
INSERT INTO diff_numeric_primary VALUES (-0.00);
INSERT INTO diff_numeric_primary VALUES (0.000);
SELECT v=0 FROM diff_numeric_primary ORDER BY v;
CREATE TABLE diff_numeric_unique (id INT PRIMARY KEY,v NUMERIC UNIQUE);
INSERT INTO diff_numeric_unique VALUES (1,0.50);
INSERT INTO diff_numeric_unique VALUES (2,0.500);
INSERT INTO diff_numeric_unique VALUES (3,NULL),(4,NULL);
SELECT id FROM diff_numeric_unique ORDER BY id;
CREATE TABLE diff_numeric_secondary (id INT PRIMARY KEY,v NUMERIC);
INSERT INTO diff_numeric_secondary VALUES (1,0.50),(2,0.500),(3,2.00);
CREATE INDEX diff_numeric_secondary_idx ON diff_numeric_secondary(v);
SELECT id FROM diff_numeric_secondary WHERE v=0.5 ORDER BY id;
SELECT id FROM diff_numeric_secondary WHERE v=0.5000 ORDER BY id;
BEGIN;
INSERT INTO diff_numeric_secondary VALUES (4,0.50000);
ROLLBACK;
UPDATE diff_numeric_secondary SET v=3.00 WHERE id=2;
SELECT id FROM diff_numeric_secondary WHERE v=0.5000;
SELECT id FROM diff_numeric_secondary WHERE v=3.000;
DROP TABLE diff_numeric_primary;
DROP TABLE diff_numeric_unique;
DROP TABLE diff_numeric_secondary;
