CREATE TABLE diff_pg_class_query(id INT);
CREATE TABLE diff_pg_class_query_b(id INT,v TEXT);
SELECT count(*) FROM pg_class WHERE relname='diff_pg_class_query';
SELECT count(*) FROM pg_class WHERE relname='diff_pg_class_query' AND FALSE;
SELECT count(NULL),count(relname) FROM pg_class WHERE relname='diff_pg_class_query';
SELECT relname,relkind,relpersistence,relnatts FROM pg_class WHERE relname='diff_pg_class_query';
SELECT relname::text AS "Label Name",relkind::text,relpersistence::text FROM pg_catalog.pg_class WHERE relname='diff_pg_class_query';
SELECT c.relname::text FROM pg_class AS c WHERE c.relname='diff_pg_class_query';
/* FROM SELECT */ SELECT relname::text FROM pg_class WHERE relname='diff_pg_class_query';
SELECT relname::text FROM pg_class WHERE relname='diff_pg_class_query' OR relname='diff_pg_class_query_b' ORDER BY 1 DESC LIMIT 1 OFFSET 1;
SELECT relname::text,nullif(relnatts,1) AS n FROM pg_class WHERE relname='diff_pg_class_query' OR relname='diff_pg_class_query_b' ORDER BY n DESC;
SELECT relname::text,nullif(relnatts,1) AS n FROM pg_class WHERE relname='diff_pg_class_query' OR relname='diff_pg_class_query_b' ORDER BY n DESC NULLS LAST;
SELECT relname::text FROM pg_class WHERE relname='diff_pg_class_query' ORDER BY 0;
SELECT relname::text FROM pg_class WHERE relname='diff_pg_class_query' AND NULL;
SELECT NULL::text AS absent FROM pg_class WHERE relname='diff_pg_class_query';
SELECT missing_catalog_column FROM pg_class WHERE FALSE;
SELECT wrong.relname FROM pg_class WHERE FALSE;
SELECT relname FROM pg_class WHERE relname;
SELECT relname::text FROM pg_class WHERE NULL;
SELECT relname FROM pg_class WHERE NULL::text;
BEGIN READ ONLY;
SELECT count(*) FROM pg_class WHERE relname='diff_pg_class_query';
ROLLBACK;
DROP TABLE diff_pg_class_query;
DROP TABLE diff_pg_class_query_b;
