DROP TABLE IF EXISTS public.diff_qfr_inline;
DROP TABLE IF EXISTS public.diff_qfr_named;
DROP TABLE IF EXISTS public.diff_qfr_table;
DROP TABLE IF EXISTS public.diff_qfr_alter;
DROP SCHEMA IF EXISTS diff_qfr CASCADE;
CREATE SCHEMA diff_qfr;
CREATE TABLE diff_qfr.parent (id integer PRIMARY KEY);
CREATE TABLE public.diff_qfr_inline (id integer REFERENCES diff_qfr.parent(id));
CREATE TABLE public.diff_qfr_named (id integer, CONSTRAINT diff_qfr_named_fkey FOREIGN KEY (id) REFERENCES diff_qfr.parent(id));
CREATE TABLE public.diff_qfr_table (id integer, FOREIGN KEY (id) REFERENCES diff_qfr.parent(id));
CREATE TABLE public.diff_qfr_alter (id integer);
ALTER TABLE public.diff_qfr_alter ADD CONSTRAINT diff_qfr_alter_fkey FOREIGN KEY (id) REFERENCES diff_qfr.parent(id);
INSERT INTO diff_qfr.parent VALUES (1);
INSERT INTO public.diff_qfr_inline VALUES (1);
INSERT INTO public.diff_qfr_named VALUES (1);
INSERT INTO public.diff_qfr_table VALUES (1);
INSERT INTO public.diff_qfr_alter VALUES (1);
SELECT id FROM public.diff_qfr_inline;
SELECT id FROM public.diff_qfr_named;
SELECT id FROM public.diff_qfr_table;
SELECT id FROM public.diff_qfr_alter;
