CREATE TABLE diff_quoted_predicate("child id" INT PRIMARY KEY,payload TEXT);
INSERT INTO diff_quoted_predicate VALUES(1,'original');
UPDATE diff_quoted_predicate SET payload='changed' WHERE "child id"=1;
SELECT "child id",payload FROM diff_quoted_predicate;
DELETE FROM diff_quoted_predicate WHERE "child id"=1;
SELECT "child id",payload FROM diff_quoted_predicate;
DROP TABLE diff_quoted_predicate;
CREATE TABLE diff_quoted_special("child id" INT PRIMARY KEY,payload TEXT,"nullable text" TEXT,"a""b" TEXT,"key.name" INT);
INSERT INTO diff_quoted_special VALUES(1,'original',NULL,'has space',7),(2,'other','','plain',8);
UPDATE diff_quoted_special SET payload='empty' WHERE "nullable text"='' RETURNING "child id";
UPDATE diff_quoted_special SET payload='null' WHERE "nullable text" IS NULL RETURNING "child id";
UPDATE diff_quoted_special SET payload='like' WHERE "a""b" LIKE 'has space%' RETURNING "child id";
DELETE FROM diff_quoted_special WHERE "key.name"=7 AND "child id"<>2 RETURNING "child id",payload;
DELETE FROM diff_quoted_special WHERE "nullable text" IS NULL;
DELETE FROM diff_quoted_special WHERE "nullable text" IS NOT NULL RETURNING "child id";
SELECT "child id" FROM diff_quoted_special;
DROP TABLE diff_quoted_special;
CREATE TABLE diff_quoted_fk_parent("key id" INT PRIMARY KEY);
INSERT INTO diff_quoted_fk_parent VALUES(1);
CREATE TABLE diff_quoted_fk_child("child id" INT PRIMARY KEY,"parent id" INT REFERENCES diff_quoted_fk_parent("key id"));
INSERT INTO diff_quoted_fk_child VALUES(1,1);
BEGIN;
SAVEPOINT quoted_sp;
UPDATE diff_quoted_fk_child SET "parent id"=999 WHERE "child id"=1 RETURNING "child id";
ROLLBACK TO SAVEPOINT quoted_sp;
SELECT "child id","parent id" FROM diff_quoted_fk_child;
COMMIT;
DELETE FROM diff_quoted_fk_child WHERE "child id">=1 AND "child id"<=1 RETURNING "child id";
DROP TABLE diff_quoted_fk_parent,diff_quoted_fk_child;
