DROP SCHEMA IF EXISTS "Diff.Seq.Schema" CASCADE;
DROP SCHEMA IF EXISTS "Diff" CASCADE;
CREATE SCHEMA "Diff.Seq.Schema";
CREATE SCHEMA "Diff";
CREATE SEQUENCE "Diff.Seq.Schema".seq_start START 5;
CREATE SEQUENCE "Diff"."Seq.Schema.seq_start" START 11;
SELECT nextval('"Diff.Seq.Schema".seq_start');
SELECT nextval('"Diff"."Seq.Schema.seq_start"');
SELECT currval('"Diff.Seq.Schema".seq_start');
SELECT currval('"Diff"."Seq.Schema.seq_start"');
ALTER SEQUENCE "Diff.Seq.Schema".seq_start RESTART WITH 9;
SELECT nextval('"Diff.Seq.Schema".seq_start');
SELECT nextval('"Diff"."Seq.Schema.seq_start"');
ALTER SEQUENCE "Diff.Seq.Schema".seq_start RENAME TO seq_renamed;
SELECT nextval('"Diff.Seq.Schema".seq_renamed');
DROP SEQUENCE "Diff.Seq.Schema".seq_renamed;
DROP SEQUENCE "Diff"."Seq.Schema.seq_start";
DROP SCHEMA "Diff.Seq.Schema";
DROP SCHEMA "Diff";
SELECT 1;
