CREATE TABLE repeated_begin_options(id INT PRIMARY KEY);
BEGIN READ ONLY;
BEGIN;
INSERT INTO repeated_begin_options VALUES(1);
ROLLBACK;
BEGIN READ ONLY;
BEGIN READ WRITE;
INSERT INTO repeated_begin_options VALUES(1);
ROLLBACK;
BEGIN;
INSERT INTO repeated_begin_options VALUES(10);
SAVEPOINT keep;
INSERT INTO repeated_begin_options VALUES(20);
START TRANSACTION;
ROLLBACK TO keep;
SELECT id FROM repeated_begin_options ORDER BY id;
ROLLBACK;
BEGIN READ ONLY;
SELECT id FROM repeated_begin_options;
BEGIN READ WRITE;
ROLLBACK;
BEGIN;
SELECT id FROM repeated_begin_options;
BEGIN ISOLATION LEVEL SERIALIZABLE;
ROLLBACK;
SELECT id FROM repeated_begin_options;
DROP TABLE repeated_begin_options;
