CREATE TABLE savepoint_read_only_modes(id INT PRIMARY KEY);
BEGIN READ WRITE;
SAVEPOINT mode;
SET TRANSACTION READ ONLY;
ROLLBACK TO mode;
INSERT INTO savepoint_read_only_modes VALUES(1);
ROLLBACK;
BEGIN;
SAVEPOINT mode;
SET TRANSACTION READ ONLY;
INSERT INTO savepoint_read_only_modes VALUES(1);
COMMIT AND CHAIN;
INSERT INTO savepoint_read_only_modes VALUES(1);
ROLLBACK;
BEGIN;
SAVEPOINT mode;
SET TRANSACTION READ ONLY;
RELEASE mode;
INSERT INTO savepoint_read_only_modes VALUES(1);
ROLLBACK;
BEGIN READ ONLY;
SAVEPOINT mode;
SET TRANSACTION READ WRITE;
ROLLBACK TO mode;
INSERT INTO savepoint_read_only_modes VALUES(1);
ROLLBACK;
BEGIN;
SAVEPOINT outer_mode;
SET TRANSACTION READ ONLY;
SAVEPOINT inner_mode;
ROLLBACK TO inner_mode;
INSERT INTO savepoint_read_only_modes VALUES(1);
ROLLBACK TO outer_mode;
INSERT INTO savepoint_read_only_modes VALUES(1);
ROLLBACK;
SELECT id FROM savepoint_read_only_modes;
DROP TABLE savepoint_read_only_modes;
