BEGIN;
CREATE SEQUENCE diff_seq_rollback_identity;
SELECT nextval('diff_seq_rollback_identity');
ROLLBACK;
SELECT nextval('diff_seq_rollback_identity');
CREATE SEQUENCE diff_seq_rollback_identity;
SELECT currval('diff_seq_rollback_identity');
SELECT nextval('diff_seq_rollback_identity');
DROP SEQUENCE diff_seq_rollback_identity;
CREATE SEQUENCE diff_seq_identity_survivor START 41;
SELECT nextval('diff_seq_identity_survivor');
BEGIN;
SAVEPOINT diff_seq_identity_sp;
CREATE SEQUENCE diff_seq_identity_savepoint;
SELECT nextval('diff_seq_identity_savepoint');
ROLLBACK TO SAVEPOINT diff_seq_identity_sp;
SELECT nextval('diff_seq_identity_savepoint');
ROLLBACK TO SAVEPOINT diff_seq_identity_sp;
CREATE SEQUENCE diff_seq_identity_savepoint;
SELECT currval('diff_seq_identity_savepoint');
ROLLBACK TO SAVEPOINT diff_seq_identity_sp;
COMMIT;
SELECT currval('diff_seq_identity_survivor');
DROP SEQUENCE diff_seq_identity_survivor;
