CREATE TABLE diff_serial_owned_sequence(id SERIAL PRIMARY KEY,code TEXT);
INSERT INTO diff_serial_owned_sequence(code) VALUES('kept');
SELECT id,code FROM diff_serial_owned_sequence;
SELECT currval('diff_serial_owned_sequence_id_seq');
SELECT nextval('diff_serial_owned_sequence_id_seq');
INSERT INTO diff_serial_owned_sequence(code) VALUES('next') RETURNING id;
DROP TABLE diff_serial_owned_sequence;
SELECT nextval('diff_serial_owned_sequence_id_seq');
CREATE SEQUENCE diff_serial_collision_id_seq;
CREATE TABLE diff_serial_collision(id SERIAL);
INSERT INTO diff_serial_collision DEFAULT VALUES RETURNING id;
SELECT currval('diff_serial_collision_id_seq1');
SELECT nextval('diff_serial_collision_id_seq');
DROP TABLE diff_serial_collision;
SELECT nextval('diff_serial_collision_id_seq1');
SELECT nextval('diff_serial_collision_id_seq');
DROP SEQUENCE diff_serial_collision_id_seq;
CREATE TABLE diff_serial_types(a SMALLSERIAL,b SERIAL,c BIGSERIAL,d SERIAL2,e SERIAL4,f SERIAL8);
INSERT INTO diff_serial_types DEFAULT VALUES RETURNING a,b,c,d,e,f;
SELECT setval('diff_serial_types_a_seq',32767);
SELECT nextval('diff_serial_types_a_seq');
DROP TABLE diff_serial_types;
CREATE TABLE "表表表表表表表表表表表表"("列列列列列列列列列列列列" SERIAL);
INSERT INTO "表表表表表表表表表表表表" DEFAULT VALUES RETURNING "列列列列列列列列列列列列";
SELECT currval('表表表表表表表表表_列列列列列列列列列_seq');
DROP TABLE "表表表表表表表表表表表表";
SELECT nextval('表表表表表表表表表_列列列列列列列列列_seq');
CREATE TABLE diff_serial_bad(id SERIAL DEFAULT 7);
SELECT id FROM diff_serial_bad;
SELECT nextval('diff_serial_bad_id_seq');
CREATE TABLE diff_serial_array_bad(id SERIAL[]);
CREATE SCHEMA "diff serial schema";
CREATE TABLE "diff serial schema"."odd.table"("it's" SERIAL);
INSERT INTO "diff serial schema"."odd.table" DEFAULT VALUES RETURNING "it's";
SELECT currval('"diff serial schema"."odd.table_it''s_seq"');
DROP TABLE "diff serial schema"."odd.table";
SELECT nextval('"diff serial schema"."odd.table_it''s_seq"');
DROP SCHEMA "diff serial schema";
BEGIN;
CREATE TABLE diff_serial_rollback(id SERIAL);
INSERT INTO diff_serial_rollback DEFAULT VALUES;
ROLLBACK;
SELECT id FROM diff_serial_rollback;
SELECT nextval('diff_serial_rollback_id_seq');
CREATE TABLE diff_serial_rollback(id SERIAL);
SELECT currval('diff_serial_rollback_id_seq');
INSERT INTO diff_serial_rollback DEFAULT VALUES RETURNING id;
SELECT nextval('diff_serial_rollback_id_seq');
TRUNCATE diff_serial_rollback RESTART IDENTITY;
SELECT currval('diff_serial_rollback_id_seq');
INSERT INTO diff_serial_rollback DEFAULT VALUES RETURNING id;
BEGIN;
TRUNCATE diff_serial_rollback RESTART IDENTITY;
INSERT INTO diff_serial_rollback DEFAULT VALUES;
ROLLBACK;
SELECT id FROM diff_serial_rollback;
SELECT nextval('diff_serial_rollback_id_seq');
DROP TABLE diff_serial_rollback;
