CREATE TABLE diff_serial_null_bad(id SERIAL NULL);
SELECT id FROM diff_serial_null_bad;
SELECT nextval('diff_serial_null_bad_id_seq');
CREATE TABLE diff_smallserial_null_bad(id SMALLSERIAL NULL);
CREATE TABLE diff_bigserial_null_bad(id BIGSERIAL NULL);
CREATE TABLE diff_serial2_null_bad(id SERIAL2 NULL);
CREATE TABLE diff_serial4_null_bad(id SERIAL4 NULL);
CREATE TABLE diff_serial8_null_bad(id SERIAL8 NULL);
CREATE TABLE diff_serial_pk_null_bad(id SERIAL PRIMARY KEY NULL);
CREATE TABLE diff_serial_null_pk_bad(id SERIAL NULL PRIMARY KEY);
CREATE TABLE diff_serial_null_order_bad(id SERIAL NULL NOT NULL);
CREATE TABLE diff_serial_null_order2_bad(id SERIAL NOT NULL NULL);
CREATE TABLE diff_serial_null_alter(base INT);
ALTER TABLE diff_serial_null_alter ADD COLUMN id SERIAL NULL;
SELECT base FROM diff_serial_null_alter;
SELECT nextval('diff_serial_null_alter_id_seq');
DROP TABLE diff_serial_null_alter;
CREATE TABLE diff_serial_not_null(id SERIAL NOT NULL);
INSERT INTO diff_serial_not_null DEFAULT VALUES RETURNING id;
DROP TABLE diff_serial_not_null;
