SELECT 1 UNION SELECT 2 INTERSECT SELECT 2 ORDER BY 1;
SELECT 1 EXCEPT SELECT 1 UNION SELECT 2 ORDER BY 1;
(SELECT 1 UNION SELECT 2) INTERSECT (SELECT 2 UNION SELECT 3) ORDER BY 1;
(SELECT 1);
(SELECT 1 UNION SELECT 2) /* left operand */ INTERSECT SELECT 2;
((SELECT 2 AS n UNION ALL SELECT 1)) ORDER BY n LIMIT 1;
SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 2 ORDER BY 1;
(SELECT 2 AS n UNION ALL SELECT 1 ORDER BY n LIMIT 1) UNION ALL SELECT 3 ORDER BY n;
