-- OFFSET applies to the combined set result after ORDER BY.
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v LIMIT 1 OFFSET 1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v OFFSET 1 LIMIT 1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v OFFSET 1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v OFFSET 0;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v OFFSET NULL;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v OFFSET -1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v LIMIT ALL OFFSET 1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v LIMIT NULL OFFSET 1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v LIMIT 0 OFFSET 1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v OFFSET 2 LIMIT 1;
