-- OFFSET applies to the combined set result after ORDER BY.
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v LIMIT 1 OFFSET 1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v OFFSET 1 LIMIT 1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v OFFSET 1;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v OFFSET 0;
