-- PostgreSQL treats LIMIT ALL and LIMIT NULL as unbounded.
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v LIMIT ALL;
SELECT 1 AS v UNION ALL SELECT 2 AS v ORDER BY v LIMIT NULL;
SELECT 1 AS v INTERSECT SELECT 1 AS v LIMIT ALL;
SELECT 1 AS v EXCEPT SELECT 2 AS v LIMIT NULL;
