SELECT repeat('ab', 3);
SELECT reverse('abc');
SELECT lpad('hi', 5, '*'), rpad('hi', 5, '*');
SELECT concat_ws(',', 'a', NULL, 'b');
SELECT left('abcdef', 3), right('abcdef', 2);
SELECT substring('hello', 2, 3), btrim('  x  ');
SELECT starts_with('abc', 'ab'), md5('abc');
SELECT ascii('A'), chr(66), format('%s-%s', 'a', 'b');
SELECT 'a' ~ '^a', regexp_replace('aaa', 'a', 'b');
SELECT split_part('a,b,c', ',', 2), position('b' in 'abc');
SELECT date '2026-01-31' + interval '1 month';
SELECT timestamp '2026-01-01 10:00:00' - interval '90 minutes';
SELECT extract(year from date '2026-05-06'), date_part('month', date '2026-05-06');
SELECT (interval '1 day' * 3);
SELECT justify_hours(interval '25 hours');
SELECT numeric '10.5' / 3;
SELECT div(numeric '10.5', 3), mod(numeric '10.5', 3);
SELECT ceil(2.1), floor(2.9), round(2.5), trunc(2.7), width_bucket(5.5, 0, 10, 4);
SELECT NULLIF(1, 1), COALESCE(NULL, 3), greatest(1, 5, 3), least(1, 5, 3);
