CREATE TABLE diff_prepare_permanent(id INT PRIMARY KEY);
CREATE TEMP TABLE diff_prepare_temp(id SERIAL PRIMARY KEY);
CREATE TEMP TABLE diff_prepare_empty(id INT);
INSERT INTO diff_prepare_temp DEFAULT VALUES RETURNING id;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(100);
PREPARE TRANSACTION 'diff_temp_prepare_positive';
ROLLBACK PREPARED 'diff_temp_prepare_positive';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(1);
SELECT id FROM diff_prepare_temp;
PREPARE TRANSACTION 'diff_temp_prepare_read';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(2);
SELECT id FROM pg_temp.diff_prepare_temp WHERE FALSE;
PREPARE TRANSACTION 'diff_temp_prepare_false';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(3);
SELECT count(*) FROM diff_prepare_empty;
PREPARE TRANSACTION 'diff_temp_prepare_empty';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(4);
SELECT nextval('pg_temp.diff_prepare_temp_id_seq');
PREPARE TRANSACTION 'diff_temp_prepare_nextval';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(5);
SELECT currval('diff_prepare_temp_id_seq');
PREPARE TRANSACTION 'diff_temp_prepare_currval';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(6);
SELECT lastval();
PREPARE TRANSACTION 'diff_temp_prepare_lastval';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(7);
SELECT setval('diff_prepare_temp_id_seq',20,FALSE);
PREPARE TRANSACTION 'diff_temp_prepare_setval';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(8);
SAVEPOINT child;
SELECT id FROM diff_prepare_empty;
ROLLBACK TO child;
PREPARE TRANSACTION 'diff_temp_prepare_child_read';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(9);
SAVEPOINT child;
INSERT INTO diff_prepare_empty VALUES(9);
ROLLBACK TO child;
PREPARE TRANSACTION 'diff_temp_prepare_child_write';
SELECT id FROM diff_prepare_permanent;
SELECT id FROM diff_prepare_empty;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(10);
SAVEPOINT child;
CREATE TEMP TABLE diff_prepare_child(id INT);
ROLLBACK TO child;
PREPARE TRANSACTION 'diff_temp_prepare_child_create';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(11);
UPDATE diff_prepare_empty SET id=2 WHERE id=999;
PREPARE TRANSACTION 'diff_temp_prepare_zero_update';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(12);
DELETE FROM diff_prepare_empty WHERE id=999;
PREPARE TRANSACTION 'diff_temp_prepare_zero_delete';
SELECT id FROM diff_prepare_permanent;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(13);
LOCK TABLE diff_prepare_temp IN SHARE MODE;
PREPARE TRANSACTION 'diff_temp_prepare_lock';
SELECT id FROM diff_prepare_permanent;
BEGIN;
CREATE TEMP TABLE diff_prepare_commit_drop(id INT) ON COMMIT DROP;
PREPARE TRANSACTION 'diff_temp_prepare_on_commit';
SELECT id FROM diff_prepare_commit_drop;
BEGIN;
INSERT INTO diff_prepare_permanent VALUES(200);
PREPARE TRANSACTION 'diff_temp_prepare_reset';
COMMIT PREPARED 'diff_temp_prepare_reset';
SELECT id FROM diff_prepare_permanent;
BEGIN;
PREPARE diff_prepare_temp_analysis AS SELECT id FROM diff_prepare_empty;
PREPARE TRANSACTION 'diff_temp_prepare_sql_analysis';
SELECT id FROM diff_prepare_empty;
DROP TABLE diff_prepare_temp;
DROP TABLE diff_prepare_empty;
DROP TABLE diff_prepare_permanent;
