CREATE TEMP TABLE diff_temp_index_catalog(id INT,v TEXT);
INSERT INTO diff_temp_index_catalog VALUES(1,'kept'),(2,'other');
CREATE INDEX diff_temp_index_catalog_index ON diff_temp_index_catalog(id);
SELECT count(*) FROM pg_class WHERE relname='diff_temp_index_catalog_index' AND relkind='i' AND relpersistence='t';
BEGIN;
SAVEPOINT before_drop;
DROP INDEX pg_temp.diff_temp_index_catalog_index;
SELECT count(*) FROM pg_class WHERE relname='diff_temp_index_catalog_index' AND relkind='i' AND relpersistence='t';
ROLLBACK TO before_drop;
SELECT count(*) FROM pg_class WHERE relname='diff_temp_index_catalog_index' AND relkind='i' AND relpersistence='t';
SELECT id,v FROM diff_temp_index_catalog WHERE id=1;
ROLLBACK;
BEGIN;
SAVEPOINT before_discard;
DISCARD TEMP;
SELECT count(*) FROM pg_class WHERE relname='diff_temp_index_catalog_index' AND relkind='i' AND relpersistence='t';
ROLLBACK TO before_discard;
SELECT count(*) FROM pg_class WHERE relname='diff_temp_index_catalog_index' AND relkind='i' AND relpersistence='t';
SELECT id,v FROM diff_temp_index_catalog WHERE id=1;
COMMIT;
DISCARD TEMP;
SELECT count(*) FROM pg_class WHERE relname='diff_temp_index_catalog_index' AND relkind='i' AND relpersistence='t';
DROP INDEX pg_temp.diff_temp_index_catalog_index;
