-- text functions: initcap, ascii, chr, to_hex, lengths, regexp, split
SELECT initcap('hello world')
SELECT ascii('A')
SELECT chr(66)
SELECT to_hex(255)
SELECT octet_length('héllo')
SELECT bit_length('abc')
SELECT md5('abc')
SELECT regexp_matches('foobarbequebaz', '(bar)(beque)')
SELECT split_part('a~b~c', '~', 2)
SELECT split_part('a~b~c', '~', 4)
SELECT substr('alphabet', -3)
SELECT reverse('abc')
SELECT repeat('ab', 3)
SELECT concat_ws('-', 'a', NULL, 'b')
SELECT regexp_matches('abc', '(a)(b)')
SELECT regexp_matches('ABC', 'b', 'i')
