CREATE SEQUENCE diff_truncate_owned_seq START 7 INCREMENT 3;
CREATE TABLE diff_truncate_owned(id INT DEFAULT nextval('diff_truncate_owned_seq'),code TEXT);
ALTER SEQUENCE diff_truncate_owned_seq OWNED BY diff_truncate_owned.id;
INSERT INTO diff_truncate_owned(code) VALUES('before') RETURNING id;
TRUNCATE diff_truncate_owned RESTART IDENTITY;
SELECT currval('diff_truncate_owned_seq');
INSERT INTO diff_truncate_owned(code) VALUES('restart') RETURNING id;
SELECT currval('diff_truncate_owned_seq');
BEGIN;
TRUNCATE diff_truncate_owned RESTART IDENTITY;
INSERT INTO diff_truncate_owned(code) VALUES('transaction') RETURNING id;
ROLLBACK;
SELECT id,code FROM diff_truncate_owned;
SELECT nextval('diff_truncate_owned_seq');
DROP TABLE diff_truncate_owned;
CREATE SEQUENCE diff_truncate_unowned START 31 INCREMENT 2;
CREATE TABLE diff_truncate_default(id INT DEFAULT nextval('diff_truncate_unowned'));
INSERT INTO diff_truncate_default DEFAULT VALUES RETURNING id;
TRUNCATE diff_truncate_default RESTART IDENTITY;
INSERT INTO diff_truncate_default DEFAULT VALUES RETURNING id;
CREATE SCHEMA "diff restart space";
CREATE SEQUENCE "diff restart space"."seq.dot" START 19 INCREMENT 4;
CREATE TABLE "diff restart space"."table.dot"("id value" INT DEFAULT nextval('"diff restart space"."seq.dot"'));
ALTER SEQUENCE "diff restart space"."seq.dot" OWNED BY "diff restart space"."table.dot"."id value";
INSERT INTO "diff restart space"."table.dot" DEFAULT VALUES RETURNING "id value";
TRUNCATE "diff restart space"."table.dot",diff_truncate_default RESTART IDENTITY;
INSERT INTO "diff restart space"."table.dot" DEFAULT VALUES RETURNING "id value";
INSERT INTO diff_truncate_default DEFAULT VALUES RETURNING id;
TRUNCATE "diff restart space"."table.dot" CONTINUE IDENTITY;
INSERT INTO "diff restart space"."table.dot" DEFAULT VALUES RETURNING "id value";
DROP TABLE "diff restart space"."table.dot",diff_truncate_default;
DROP SCHEMA "diff restart space";
DROP SEQUENCE diff_truncate_unowned;
CREATE SEQUENCE diff_restart_parent_seq START 11;
CREATE SEQUENCE diff_restart_child_seq START 21;
CREATE TABLE diff_restart_parent(id INT PRIMARY KEY DEFAULT nextval('diff_restart_parent_seq'));
CREATE TABLE diff_restart_child(id INT PRIMARY KEY DEFAULT nextval('diff_restart_child_seq'),pid INT REFERENCES diff_restart_parent(id));
ALTER SEQUENCE diff_restart_parent_seq OWNED BY diff_restart_parent.id;
ALTER SEQUENCE diff_restart_child_seq OWNED BY diff_restart_child.id;
INSERT INTO diff_restart_parent DEFAULT VALUES RETURNING id;
INSERT INTO diff_restart_child(pid) VALUES(11) RETURNING id;
TRUNCATE diff_restart_parent RESTART IDENTITY CASCADE;
INSERT INTO diff_restart_parent DEFAULT VALUES RETURNING id;
INSERT INTO diff_restart_child(pid) VALUES(11) RETURNING id;
DROP TABLE diff_restart_parent,diff_restart_child;
CREATE SEQUENCE diff_restart_descending_seq START -7 INCREMENT -3;
CREATE TABLE diff_restart_descending(id INT DEFAULT nextval('diff_restart_descending_seq'));
ALTER SEQUENCE diff_restart_descending_seq OWNED BY diff_restart_descending.id;
INSERT INTO diff_restart_descending DEFAULT VALUES RETURNING id;
SELECT nextval('diff_restart_descending_seq');
TRUNCATE diff_restart_descending RESTART IDENTITY;
INSERT INTO diff_restart_descending DEFAULT VALUES RETURNING id;
DROP TABLE diff_restart_descending;
