CREATE TABLE diff_update_computed(id INT PRIMARY KEY,code TEXT,d DATE);
INSERT INTO diff_update_computed VALUES(1,'original','2024-01-01'),(2,'original','2025-02-02'),(3,NULL,NULL);
UPDATE diff_update_computed SET code='changed' WHERE d=CAST('2025-02-02' AS date);
SELECT id,code FROM diff_update_computed ORDER BY id;
UPDATE diff_update_computed SET code='original';
UPDATE diff_update_computed SET code='changed' WHERE id=CAST(2 AS integer);
SELECT id,code FROM diff_update_computed ORDER BY id;
UPDATE diff_update_computed SET code='original';
UPDATE diff_update_computed SET code='changed' WHERE id=1+1;
SELECT id,code FROM diff_update_computed ORDER BY id;
DROP TABLE diff_update_computed;
CREATE TABLE diff_update_computed_more(id INT PRIMARY KEY,code TEXT,n NUMERIC);
INSERT INTO diff_update_computed_more VALUES(1,'original',1),(2,'original',2),(3,NULL,NULL);
UPDATE diff_update_computed_more SET code='case' WHERE CASE WHEN id=2 THEN true ELSE false END;
SELECT id,code FROM diff_update_computed_more ORDER BY id;
UPDATE diff_update_computed_more SET code='divide' WHERE n/0.5>2;
SELECT id,code FROM diff_update_computed_more ORDER BY id;
UPDATE diff_update_computed_more SET code='lazy' WHERE coalesce(1,1/0)=1 AND id=2;
SELECT id,code FROM diff_update_computed_more ORDER BY id;
UPDATE diff_update_computed_more SET code='overlap' WHERE id=1+1 OR id>1;
SELECT id,code FROM diff_update_computed_more ORDER BY id;
UPDATE diff_update_computed_more SET code='bad' WHERE n/0>1;
SELECT id,code FROM diff_update_computed_more ORDER BY id;
UPDATE diff_update_computed_more SET code='bad' WHERE id=CAST('bad' AS integer);
SELECT id,code FROM diff_update_computed_more ORDER BY id;
DROP TABLE diff_update_computed_more;
