-- window function frame semantics
DROP TABLE IF EXISTS w1
CREATE TABLE w1 (k INT, v INT)
INSERT INTO w1 VALUES (1,10),(2,20),(3,30),(4,40)
SELECT sum(v) OVER (ORDER BY k ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM w1 ORDER BY k
SELECT sum(v) OVER (ORDER BY k ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) FROM w1 ORDER BY k
SELECT avg(v) OVER (ORDER BY k RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM w1 ORDER BY k
SELECT lag(v) OVER (ORDER BY k), lead(v) OVER (ORDER BY k) FROM w1 ORDER BY k
SELECT first_value(v) OVER (ORDER BY k), last_value(v) OVER (ORDER BY k) FROM w1 ORDER BY k
SELECT nth_value(v, 2) OVER (ORDER BY k) FROM w1 ORDER BY k
DROP TABLE IF EXISTS w2
CREATE TABLE w2 (k INT, v INT)
INSERT INTO w2 VALUES (1,10),(1,15),(2,20)
SELECT nth_value(v, 2) OVER (ORDER BY k) FROM w2 ORDER BY v
SELECT nth_value(v, 3) OVER (ORDER BY k ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM w2 ORDER BY v
DROP TABLE w2
DROP TABLE w1
