DROP TABLE IF EXISTS diff_win3;
CREATE TABLE diff_win3 (id INT, v INT);
INSERT INTO diff_win3 VALUES (1, 10), (2, 20), (3, 30), (4, 10), (5, NULL);
SELECT id, min(v) OVER (ORDER BY v RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM diff_win3;
SELECT id, max(v) OVER (ORDER BY v RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM diff_win3;
SELECT id, sum(v) OVER (ORDER BY v RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM diff_win3;
SELECT id, count(v) OVER (ORDER BY v RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM diff_win3;
SELECT array_agg(v) OVER (ORDER BY id) FROM diff_win3;
